"""Unit and integration tests for course page rendering and site integration."""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

COURSE_15040 = ROOT / "content" / "jiangsu" / "courses" / "15040"
SOURCES_15040 = ROOT / "sources" / "jiangsu" / "courses" / "15040"


def test_render_is_deterministic(tmp_path: Path):
    """连续渲染两次，除 generated_at 行外字节一致。"""
    from lib.course_pipeline.render_pages import render_course_pages

    dir1 = tmp_path / "run1"
    dir2 = tmp_path / "run2"
    shutil.copytree(COURSE_15040, dir1)
    shutil.copytree(COURSE_15040, dir2)

    render_course_pages(ROOT, "15040", target_dir=dir1)
    render_course_pages(ROOT, "15040", target_dir=dir2)

    files1 = sorted(p.relative_to(dir1).as_posix() for p in dir1.glob("**/*") if p.is_file())
    files2 = sorted(p.relative_to(dir2).as_posix() for p in dir2.glob("**/*") if p.is_file())
    assert files1 == files2

    for rel in files1:
        t1 = (dir1 / rel).read_text(encoding="utf-8")
        t2 = (dir2 / rel).read_text(encoding="utf-8")
        assert t1 == t2, f"Nondeterministic rendering output for {rel}"


def test_manual_block_preserved(tmp_path: Path):
    """在 manual:begin/end 内写入哨兵文本 → 重渲染后仍在原位且内容不变。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    sentinel = "<!-- SENTINEL_MANUAL_TEXT_99999 -->"
    review_file = work_dir / "review.md"
    orig_text = review_file.read_text(encoding="utf-8")
    if "<!-- manual:begin" in orig_text:
        modified = re.sub(
            r"(<!-- manual:begin id=[a-zA-Z0-9_-]+ -->)",
            rf"\1\n{sentinel}\n",
            orig_text,
            count=1,
        )
    else:
        modified = orig_text + f"\n<!-- manual:begin id=schedules -->\n{sentinel}\n<!-- manual:end -->\n"
    review_file.write_text(modified, encoding="utf-8")

    render_course_pages(ROOT, "15040", target_dir=work_dir)
    rendered_text = (work_dir / "review.md").read_text(encoding="utf-8")
    assert sentinel in rendered_text, "Manual block sentinel text must be preserved after render"


def test_frontmatter_preserved_bytewise(tmp_path: Path):
    """15040/index.md 的 frontmatter（:1-58）在渲染前后字节一致。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    orig_text = (work_dir / "index.md").read_text(encoding="utf-8")
    orig_fm = "\n".join(orig_text.splitlines()[:58]) + "\n"

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    rendered_text = (work_dir / "index.md").read_text(encoding="utf-8")
    rendered_fm = "\n".join(rendered_text.splitlines()[:58]) + "\n"
    assert rendered_fm == orig_fm, "Frontmatter bytes must match exactly"


def test_practice_first_line_is_canonical_h1(tmp_path: Path):
    """渲染后 practice.md 首行 == `# 习近平新时代中国特色社会主义思想概论（15040）：练习与真题`；generated-by 注释在其之后。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    lines = (work_dir / "practice.md").read_text(encoding="utf-8").splitlines()
    assert lines[0] == "# 习近平新时代中国特色社会主义思想概论（15040）：练习与真题"
    assert any("<!-- generated by scripts/build-course-content.py; do not edit -->" in line for line in lines[1:5])


def test_practice_h2_set_unchanged(tmp_path: Path):
    """渲染后 practice.md 的 H2 序列 == `["## 资料状态","## 练习流程","## 记录模板","## 边界"]`（AI 练习块必须是 `###` 层级）。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    lines = (work_dir / "practice.md").read_text(encoding="utf-8").splitlines()
    h2s = [line.strip() for line in lines if line.startswith("## ")]
    assert h2s == ["## 资料状态", "## 练习流程", "## 记录模板", "## 边界"]


def test_practice_zhenti_row_status(tmp_path: Path):
    """## 资料状态 的 历年真题 行第 4 列为 metadata-only。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    text = (work_dir / "practice.md").read_text(encoding="utf-8")
    rows = []
    for line in text.splitlines():
        if "历年真题" in line and line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if cells and cells[0] == "历年真题":
                rows.append(cells)
    assert rows, "missing 历年真题 row in practice.md"
    assert rows[0][3] == "metadata-only"


def test_contract_markers_present(tmp_path: Path):
    """index.md 含 页面导航 / sources.md / practice.md / plan.md；sources.md 含 来源 / 核验；practice.md 含 真题；plan.md 含 阶段目标。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    idx = (work_dir / "index.md").read_text(encoding="utf-8")
    for marker in ["页面导航", "sources.md", "practice.md", "plan.md"]:
        assert marker in idx, f"index.md missing marker {marker}"

    src = (work_dir / "sources.md").read_text(encoding="utf-8")
    for marker in ["来源", "核验"]:
        assert marker in src, f"sources.md missing marker {marker}"

    prac = (work_dir / "practice.md").read_text(encoding="utf-8")
    assert "真题" in prac, "practice.md missing marker 真题"

    pln = (work_dir / "plan.md").read_text(encoding="utf-8")
    assert "阶段目标" in pln, "plan.md missing marker 阶段目标"


def test_start_here_block_and_cross_links(tmp_path: Path):
    """index.md 的 ## 开始学习 四步顺序 == [考纲与范围→syllabus.md, 学习计划→plan.md, 练习与真题→practice.md, 来源与核验→sources.md]；每页互链栏包含其余四类页面且不自链。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    idx = (work_dir / "index.md").read_text(encoding="utf-8")
    assert "## 开始学习" in idx

    steps = []
    for line in idx.splitlines():
        m = re.match(r"^(\d+)\.\s+\[([^\]]+)\]\(([^)]+)\)\s*$", line.strip())
        if m:
            steps.append((m.group(2), m.group(3).split("#", 1)[0]))
    assert steps == [
        ("考纲与范围", "syllabus.md"),
        ("学习计划", "plan.md"),
        ("练习与真题", "practice.md"),
        ("来源与核验", "sources.md"),
    ]

    five_pages = ["index.md", "sources.md", "syllabus.md", "plan.md", "practice.md"]
    for page in five_pages:
        text = (work_dir / page).read_text(encoding="utf-8")
        bars = [line for line in text.splitlines() if "｜" in line and "](" in line]
        assert bars, f"{page} missing cross-link bar"
        bar = bars[0]
        hrefs = set(re.findall(r"\[[^\]]+\]\(([^)]+)\)", bar))
        expected_links = {p for p in five_pages if p != page}
        assert expected_links.issubset(hrefs), f"{page} bar missing {expected_links - hrefs}: {bar}"
        assert page not in hrefs, f"{page} bar must not self link: {bar}"


def test_ai_banner_presence_and_absence(tmp_path: Path):
    """plan.md / practice.md / review.md / knowledge/*.md 含 本页由 AI 辅助生成；index.md / syllabus.md / sources.md 不含。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    banner = "本页由 AI 辅助生成"
    for name in ["plan.md", "practice.md", "review.md"]:
        text = (work_dir / name).read_text(encoding="utf-8")
        assert banner in text, f"{name} must contain banner"

    ch_pages = list((work_dir / "knowledge").glob("*.md"))
    assert len(ch_pages) == 18
    for ch in ch_pages:
        text = ch.read_text(encoding="utf-8")
        assert banner in text, f"{ch.name} must contain banner"

    for name in ["index.md", "syllabus.md", "sources.md"]:
        text = (work_dir / name).read_text(encoding="utf-8")
        assert banner not in text, f"{name} must NOT contain banner"


def test_no_blockquote_over_80_chars(tmp_path: Path):
    """产物中不存在长度 > 80 的 > 引用块，且引用块不含 选择题|填空题|简答题|材料题|下列.*正确。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    for md_file in work_dir.rglob("*.md"):
        for line in md_file.read_text(encoding="utf-8").splitlines():
            stripped = line.lstrip()
            if stripped.startswith(">"):
                quote = stripped.lstrip(">").strip()
                assert len(quote) <= 80, f"{md_file.name} blockquote > 80 chars ({len(quote)}): {quote[:40]}..."
                assert not re.search(r"(选择题|填空题|简答题|材料题|下列.*正确)", quote), (
                    f"{md_file.name} leaked question quote: {quote}"
                )


def test_all_relative_links_resolve(tmp_path: Path):
    """遍历产物中所有 ](...) 相对链接（含 knowledge/*.md 的 ../index.md），逐个断言目标文件存在。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    for md_file in work_dir.rglob("*.md"):
        text = md_file.read_text(encoding="utf-8")
        for _label, href in re.findall(r"\[([^\]]+)\]\(([^)]+)\)", text):
            if href.startswith(("http://", "https://", "mailto:", "materials://")):
                continue
            clean_target = href.split("#", 1)[0]
            if not clean_target:
                continue
            resolved = (md_file.parent / clean_target).resolve()
            if str(resolved).startswith(str(work_dir)):
                assert resolved.is_file(), f"{md_file.relative_to(work_dir)} links {href}, but {resolved} does not exist"
            else:
                # Sibling course link (e.g. ../15043/index.md) -> resolve against real repository
                rel_file = COURSE_15040 / md_file.relative_to(work_dir)
                repo_resolved = (rel_file.parent / clean_target).resolve()
                assert repo_resolved.is_file(), f"{md_file.relative_to(work_dir)} links {href}, but {repo_resolved} does not exist"


def test_chapter_pages_link_back(tmp_path: Path):
    """每个 knowledge/<NN>-<slug>.md 含 ../index.md 回链，文件名与模型 ordinal / slug 一一对应（18 个）。"""
    from lib.course_pipeline.render_pages import render_course_pages

    work_dir = tmp_path / "course"
    shutil.copytree(COURSE_15040, work_dir)

    render_course_pages(ROOT, "15040", target_dir=work_dir)

    km = json.loads((SOURCES_15040 / "knowledge-model.json").read_text(encoding="utf-8"))
    assert len(km["chapters"]) == 18

    for ch in km["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        ch_path = work_dir / "knowledge" / fname
        assert ch_path.is_file(), f"missing chapter file {fname}"
        text = ch_path.read_text(encoding="utf-8")
        assert "../index.md" in text, f"{fname} missing ../index.md backlink"


def test_failed_build_writes_nothing(tmp_path: Path):
    """缺前置（如删掉临时副本里的 content.json）→ build 15040 --backend replay exit ≠ 0、stderr 含 stage=，且 content/jiangsu/courses/15040/** 的文件集合与 mtime 快照不变。"""
    fake_root = tmp_path / "repo"
    shutil.copytree(ROOT / "scripts", fake_root / "scripts")
    shutil.copytree(ROOT / "ops", fake_root / "ops")
    shutil.copytree(ROOT / "sources", fake_root / "sources")
    shutil.copytree(ROOT / "content", fake_root / "content")

    # Deliberately remove content.json
    (fake_root / "sources" / "jiangsu" / "courses" / "15040" / "content.json").unlink()

    course_dir = fake_root / "content" / "jiangsu" / "courses" / "15040"
    snapshot_before = {p.relative_to(course_dir): p.stat().st_mtime_ns for p in course_dir.rglob("*") if p.is_file()}

    res = subprocess.run(
        [sys.executable, "scripts/build-course-content.py", "build", "15040", "--backend", "replay"],
        cwd=fake_root,
        capture_output=True,
        text=True,
    )
    assert res.returncode != 0, f"Expected non-zero exit code, got {res.returncode}, stdout={res.stdout}, stderr={res.stderr}"
    assert "stage=" in res.stderr, f"Expected 'stage=' in stderr, got {res.stderr}"

    snapshot_after = {p.relative_to(course_dir): p.stat().st_mtime_ns for p in course_dir.rglob("*") if p.is_file()}
    assert snapshot_before == snapshot_after, "Failed build must write nothing"
