"""Deterministic course page renderer (SSOT: evidence, knowledge-model, content.json).

Partitions official facts and AI prep content.
Preserves existing manual blocks (<!-- manual:begin id=<slug> -->...<!-- manual:end -->)
and frontmatter bytewise.

**所有权规则（手工内容 vs 派生内容）**：`content/jiangsu/courses/<code>/**` 的正文分两类 —— 由三份 JSON
**确定性派生**的部分（AI 备考层页面、章页、章目索引与章链接）由本模块重写；**手写正文**（`index.md` /
`syllabus.md` / `sources.md` 的官方事实页正文，以及任何 `manual:` 块）只做原样保留。渲染器**不得**
改写手写散文（改写 = 静默篡改人工校对成果，且会把越界内容搬出闸门的可测范围）。
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

GENERATED_COMMENT = "<!-- generated by scripts/build-course-content.py; do not edit -->"
AI_BANNER = "> ⚠️ 本页由 AI 辅助生成，仅供备考参考，以官方教材与大纲为准。"
AI_BANNER_PLAN = "> ⚠️ 本页由 AI 辅助生成，依据江苏省自考官方考纲与公开教材计划整理。"
AI_BANNER_PRACTICE = "> ⚠️ 本页由 AI 辅助生成，练习题依据知识点生成，不替代真实真题。"
# AI 块的生成器脚注（spec D1 / reader outcome 7：每块在页面上带 generator / evidence_refs / review_state）
AI_BLOCK_FOOTNOTE_TEMPLATE = "<!-- ai-block {block_id} | generator={backend}/{prompt_id}.{prompt_version} | evidence_refs={refs} | review_state={review_state} -->"

MANUAL_BLOCK_RE = re.compile(
    r"<!--\s*manual:begin\s+id=([a-zA-Z0-9_-]+)\s*-->(.*?)<!--\s*manual:end\s*-->",
    re.DOTALL,
)


def extract_manual_blocks(text: str) -> dict[str, str]:
    blocks: dict[str, str] = {}
    for match in MANUAL_BLOCK_RE.finditer(text):
        blocks[match.group(1)] = match.group(2).strip("\n")
    return blocks


def get_existing_manual_blocks(target_path: Path, fallback_path: Path | None = None) -> dict[str, str]:
    blocks: dict[str, str] = {}
    if fallback_path and fallback_path.is_file():
        blocks.update(extract_manual_blocks(fallback_path.read_text(encoding="utf-8")))
    if target_path.is_file():
        blocks.update(extract_manual_blocks(target_path.read_text(encoding="utf-8")))
    return blocks


def render_manual_block(block_id: str, default_content: str, blocks: dict[str, str]) -> str:
    content = blocks.get(block_id, default_content).strip("\n")
    return f"<!-- manual:begin id={block_id} -->\n{content}\n<!-- manual:end -->"


def get_course_name(evidence: dict[str, Any], code: str) -> str:
    """课名 = **仅** `status: "verified"` 的 `facts.name`（C2-003）。

    非 `verified` 的 `value` 一律不作官方事实渲染：`name` 会进 `index.md` / `syllabus.md` 的 H1，
    而这两页是 `official_only` 页面。未验证却有值 → 回落课码，不把未验证值洗成官方事实。
    """
    facts = evidence.get("facts") or {}
    name_fact = facts.get("name")
    if isinstance(name_fact, dict) and name_fact.get("status") == "verified" and name_fact.get("value"):
        return str(name_fact["value"])
    return evidence.get("course_name") or code


def _ai_footnote(block: dict[str, Any]) -> str:
    generator = block.get("generator") or {}
    refs = " ".join(str(ref) for ref in block.get("evidence_refs") or [])
    return AI_BLOCK_FOOTNOTE_TEMPLATE.format(
        block_id=block.get("block_id", ""),
        backend=generator.get("backend", ""),
        prompt_id=generator.get("prompt_id", ""),
        prompt_version=generator.get("prompt_version", ""),
        refs=refs,
        review_state=block.get("review_state", ""),
    )


def _clean_explain_headings(text: str) -> str:
    """Demote explain subheadings (e.g. ### 要点梳理 / ### 易错点) to H4.

    This keeps the MkDocs TOC (depth 3) clean, showing only 考点 and drills.
    Only H3 is demoted: an H1/H2 emitted by a future prompt revision must not be
    collapsed into the same level as its own sub-points (QC1 F-12).
    """
    cleaned_lines = []
    for line in text.splitlines():
        m = re.match(r"^###\s+(.*)$", line)
        if m:
            cleaned_lines.append(f"#### {m.group(1).strip()}")
        else:
            cleaned_lines.append(line)
    return "\n".join(cleaned_lines)


def _chapter_index_block(model: dict[str, Any]) -> str:
    """`## 章节知识精读` 区块（章链接由知识模型派生，不是手写正文）。"""
    lines = ["## 章节知识精读", "", "本课程各章核心要点、记忆法与仿真练习：", ""]
    for ch in model["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        lines.append(f"- [{ch['title']}](knowledge/{fname})")
    return "\n".join(lines)


def _render_index(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    existing_text: str,
) -> str:
    """课程概览页（`official_only`）。

    **手写正文原样保留**：`index.md` 的正文是人工校对成果（含不可移除的合规披露），渲染器只允许
    在 frontmatter 之后插入生成标识注释、并追加派生的「章节知识精读」区块 —— 不再做任何按行号 /
    下标的定位与重写（QC3-002 / QC3-006 / C2-011）。
    """
    if existing_text.startswith("---\n"):
        end_idx = existing_text.find("\n---\n", 4)
        raw_fm = existing_text[: end_idx + 5] if end_idx != -1 else ""
        body = existing_text[len(raw_fm):] if raw_fm else existing_text
    else:
        raw_fm = ""
        body = existing_text

    body = body.lstrip("\n")
    if not body.startswith(GENERATED_COMMENT):
        body = f"{GENERATED_COMMENT}\n{body}"

    if "## 章节知识精读" not in body:
        body = body.rstrip("\n") + "\n\n" + _chapter_index_block(model) + "\n"

    if raw_fm:
        return raw_fm + body.rstrip("\n") + "\n"
    return body.rstrip("\n") + "\n"


def _render_official_page(existing_text: str, fallback: list[str]) -> str:
    """官方事实页（`syllabus.md` / `sources.md`）：既有页面原样保留，缺页时才用兜底骨架。

    旧实现用「正文含某个子串」作为早返回条件，于是官方页变成冻结快照：`evidence.json` 的放行判定
    变成 `L1`、官方 URL 已在基线里，页面却仍写着 `missing-source`（QC3-008）。这里保留既有正文，
    但**不再**复述任何课程专属的官方事实（URL / 核验日期 / 章数）—— 那类值必须来自 JSON。
    """
    text = existing_text
    if text:
        if not text.startswith(GENERATED_COMMENT):
            text = f"{GENERATED_COMMENT}\n{text}"
        return text
    return "\n".join([GENERATED_COMMENT, *fallback])


def _render_syllabus(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    existing_text: str,
) -> str:
    """考纲与范围页（`official_only`）：章目索引与章链接由知识模型派生，其余正文原样保留。"""
    course_name = get_course_name(evidence, code)
    if existing_text:
        text = existing_text
        if not text.startswith(GENERATED_COMMENT):
            text = GENERATED_COMMENT + "\n" + text
        if "## 章节知识精读" not in text:
            ch_links = _chapter_index_block(model) + "\n"
            idx = text.find("## 核验清单")
            text = (text[:idx] + ch_links + text[idx:]) if idx != -1 else (text.rstrip() + "\n\n" + ch_links)
        return text

    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：考纲与范围",
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 有界公开索引",
        "",
        "### 章目索引（考纲目录切片）",
        "",
        "| 章序 | 章名 |",
        "| --- | --- |",
    ]
    for ch in model["chapters"]:
        out.append(f"| {ch['index']} | {ch['title']} |")
    out.extend(["", _chapter_index_block(model), ""])
    return "\n".join(out)


def _render_sources(
    code: str,
    evidence: dict[str, Any],
    existing_text: str,
) -> str:
    """来源与核验页（`official_only`）：既有正文原样保留；兜底骨架只写**本课程** JSON 里的官方来源。"""
    if existing_text:
        text = existing_text
        if not text.startswith(GENERATED_COMMENT):
            text = GENERATED_COMMENT + "\n" + text
        return text

    course_name = get_course_name(evidence, code)
    url = evidence.get("course_url")
    source_row = (
        f"| [{course_name} 官方考纲页]({url}) | 课程考试大纲 | match | 官方来源 |"
        if url
        else "| （缺官方公开 URL） | 官方考纲页 | 未声明 | 命名缺口：缺 jseea.cn 权威 URL |"
    )
    fallback = [
        f"# {course_name}（{code}）：来源与核验",
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md)",
        "",
        "## 来源清单",
        "",
        "| 官方 URL | 标题 | 课程代码/名称匹配 | 支撑字段 |",
        "| --- | --- | --- | --- |",
        source_row,
        "",
        "## 核验规则",
        "",
        "- 官方来源优先级：江苏省教育考试院官方 > 主考学校 > 人工校对。",
        "- 内部资料只写 `materials://...`，不得写 GitHub private raw URL。",
        "",
    ]
    return _render_official_page("", fallback)


def _render_plan(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
) -> str:
    """`plan.md`（AI 备考层）：五阶段 `stage_plan[]` 逐段呈现 + 按章学习序列。

    spec reader outcome 1：每阶段含输入 / 做法 / 输出物 / 完成标准。页面上逐块带生成器脚注
    （`generator` / `evidence_refs` / `review_state`，reader outcome 7）。课程专属数字（章数）取自知识模型，
    不再写死任何课码的字面量（C2-014）。
    """
    course_name = get_course_name(evidence, code)
    chapters = model["chapters"]
    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：学习计划",
        "",
        AI_BANNER_PLAN,
        "",
        "[返回课程概览](index.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 状态 |",
        "| --- | --- | --- |",
        "| 官方来源 | 见 [来源与核验](sources.md) | 待按来源页复核 |",
        "| 教材/考纲 | 公开页仅保留元数据与 `materials://` 索引 | 不发布原件 |",
        "| 真题 | 见 [练习与真题](practice.md) | 仅做索引，不转载题文 |",
        "",
        "## 如何使用",
        "",
        f"按 [考纲与范围](syllabus.md) 的章目索引顺序学习：每行对应一章（共 {len(chapters)} 章），"
        "通读该章大纲范围、记录不理解点，再按章末要求自检并勾选完成标记。不排周次、不绑定考期。",
        "",
        "## 阶段目标",
        "",
    ]
    for stage in content.get("stage_plan") or []:
        out.append(f"### 阶段：{stage.get('stage')}")
        out.append("")
        if stage.get("goal"):
            out.append(f"**目标**：{stage['goal']}")
            out.append("")
        for label, key in (("输入", "inputs"), ("做法", "how"), ("输出物", "outputs")):
            items = [str(item) for item in stage.get(key) or []]
            if not items:
                continue
            out.append(f"**{label}**：")
            out.append("")
            out.extend(f"- {item}" for item in items)
            out.append("")
        if stage.get("done_when"):
            out.append(f"**完成标准**：{stage['done_when']}")
            out.append("")
        out.append(_ai_footnote(stage))
        out.append("")

    out.extend(
        [
            "## 按章学习序列",
            "",
            "| 章节 | 学习任务 | 自检方式 | 完成标记 |",
            "| --- | --- | --- | --- |",
        ]
    )
    for ch in chapters:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(
            f"| {ch['title']} | [进入考点精读与自测](knowledge/{fname})；通读该章大纲范围；记录不理解点；自检章末要求。 | 能对照章名说出该章大纲范围，并列出待查项。 | ☐ |"
        )
    out.extend(
        [
            "",
            "## 空态与缺口",
            "",
            "- 不发布 PDF 原文、截图、第三方题文或私仓 raw 链接。",
            "- 教材空态：缺 ISBN → 无法排出按教材页码的周计划；学习脊柱仍为上表章目索引。",
            "- 真题空态：缺授权索引 → 无法排出真题周。",
            "- 适用考期 `未声明` → 复习节奏不绑定具体考次。",
            "- 新资料先进入 private `zikao-materials`，公开仓只写元数据与 `materials://` 引用。",
            "",
        ]
    )
    return "\n".join(out)


def _render_practice(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
) -> str:
    """`practice.md`（AI 备考层）：AI `drill` 块作为 `## 练习流程` 下的 `###` 子区块 + 折叠答案。

    H2 序列必须恰为 `## 资料状态` / `## 练习流程` / `## 记录模板` / `## 边界`
    （plan § Data contracts 5 第 8 条 / `tests/test_practice_index_framework.py`）：
    AI 练习块只能落在 `###` 层级，不得新增 H2。
    """
    course_name = get_course_name(evidence, code)
    chapters = model["chapters"]
    drills_by_point: dict[str, dict[str, Any]] = {}
    for block in content.get("blocks") or []:
        if block.get("kind") == "drill" and block.get("point_id"):
            drills_by_point[block["point_id"]] = block

    out = [
        f"# {course_name}（{code}）：练习与真题",
        GENERATED_COMMENT,
        "",
        AI_BANNER_PRACTICE,
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 来源 | 状态 |",
        "| --- | --- | --- | --- |",
        "| 历年真题 | 待补公开链接或 `materials://` 索引 | 官方公开来源 / `zikao-materials` | metadata-only |",
        "| 练习记录 | 学习者自建训练记录 | 本地笔记 | 待整理 |",
        "| 错题表 | 按错因归类，不复制版权题文 | 本地笔记 | 待整理 |",
        "",
        "## 练习流程",
        "",
        "| 阶段 | 任务 | 验收 |",
        "| --- | --- | --- |",
        "| 建索引 | 汇总可用真题年份、来源、格式 | 每条材料有来源与状态 |",
        "| 一刷 | 按章节或题型练习 | 标记错题与不确定题 |",
        "| 归因 | 将错题归入概念、计算/流程、审题、记忆四类 | 每题有错因 |",
        "| 二刷 | 只刷错题与不确定题 | 错题通过率提升 |",
        "| 限时 | 按考试时长做综合练习 | 有用时、得分、订正记录 |",
        "",
    ]

    rendered = 0
    for ch in chapters:
        for sec in ch.get("sections") or []:
            for point in sec.get("points") or []:
                drill = drills_by_point.get(point["id"])
                if not drill:
                    continue
                rendered += 1
                out.append(f"### 练习题：{point['id']}（{drill.get('question_type', '题型自测')}）")
                out.append("")
                out.append(f"**章节**：{ch['title']} ｜ **考核点**：{point.get('title', '')}")
                out.append("")
                out.append(str(drill.get("text_md", "")).strip())
                out.append("")
                out.append("<details>")
                out.append("<summary>点击查看参考答案与解析</summary>")
                out.append("")
                out.append("**【参考答案与解析】**")
                out.append("")
                out.append(str(drill.get("answer_md", "")).strip())
                out.append("")
                out.append("</details>")
                out.append("")
                out.append(_ai_footnote(drill))
                out.append("")

    if not rendered:
        out.extend(["（本课程暂无 AI 仿真练习题。）", ""])

    out.extend(
        [
            "### AI 仿真训练索引",
            "",
            f"各章练习题与折叠解析同时整理在对应章知识精读页中（共 {len(chapters)} 章）：",
            "",
        ]
    )
    for ch in chapters:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(f"- [{ch['title']} 练习题](knowledge/{fname}#ai)")
    out.extend(
        [
            "",
            "## 记录模板",
            "",
            "| 日期 | 材料 | 范围 | 用时 | 结果 | 下一步 |",
            "| --- | --- | --- | --- | --- | --- |",
            "| 待填 | 待填 | 待填 | 待填 | 待填 | 待填 |",
            "",
            "## 边界",
            "",
            "- 公开仓不粘贴真题正文、答案全文、PDF 截图。",
            "- 可写年份、来源、页码、主题标签和 `materials://` 索引。",
            "",
        ]
    )
    return "\n".join(out)


def _render_review(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    """`review.md`（AI 备考层）：`review_schedule` 的 30 / 14 / 7 三档排程，或命名缺口。

    `status == "named_gap"` 时**只**呈现缺口与缺口影响 + 下一份证据，**不编造日期**（spec reader outcome 6 /
    GC3）。`review_schedule` 是排程的主源；人工排程模板只保留在 `manual:schedules` 块内（其 `id` 是
    渲染器与人工内容的唯一接口，重渲染按 id 原样回填）。
    """
    course_name = get_course_name(evidence, code)
    schedule = content.get("review_schedule") or {}
    status = schedule.get("status")

    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：复习计划",
        "",
        AI_BANNER,
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 来源 | 状态 |",
        "| --- | --- | --- | --- |",
        "| 课程范围 | 以课程概览、考纲页和来源页为准 | `index.md` / `syllabus.md` / `sources.md` | 待核验 |",
        "| 练习材料 | 只使用公开链接或内部索引 | `practice.md` / `materials://` | metadata-only |",
        "| 错题记录 | 学习者自建错题表 | 本地笔记 | 待整理 |",
        "",
        "## 排程输入",
        "",
        "| 输入 | 取值 | 状态 |",
        "| --- | --- | --- |",
        f"| 考试日期 | {schedule.get('exam_date') or '未提供'} | {'已提供' if schedule.get('exam_date') else 'named_gap'} |",
        f"| 每周可投入学时 | {schedule.get('weekly_hours') if schedule.get('weekly_hours') else '未提供'} | {'已提供' if schedule.get('weekly_hours') else 'named_gap'} |",
        "",
    ]

    if status == "planned":
        for plan in schedule.get("plans") or []:
            out.extend(
                [
                    f"## {plan.get('horizon_days')} 天复习（{plan.get('tier')}）",
                    "",
                    f"- 起止：{plan.get('start_date')} → {plan.get('end_date')}",
                    f"- 每日建议投入：{plan.get('daily_minutes')} 分钟",
                    "",
                    "| 日 | 日期 | 重点 | 类型 |",
                    "| --- | --- | --- | --- |",
                ]
            )
            for item in plan.get("items") or []:
                out.append(f"| {item.get('day')} | {item.get('date')} | {item.get('focus')} | {item.get('kind')} |")
            out.extend(["", _ai_footnote(plan), ""])
    else:
        out.extend(
            [
                "## 命名缺口",
                "",
                "官方与用户输入均未提供排程所需的考试日期与每周学时，因此本页**不生成** 30 / 14 / 7 天计划，"
                "也不推断任何日期。",
                "",
                f"- **缺口影响**：{schedule.get('gap_impact', '')}",
                f"- **下一份需要的证据**：{schedule.get('next_evidence', '')}",
                "",
                "在缺口补齐前，复习节奏以 [学习计划](plan.md) 的五阶段流程为准，不绑定具体考次。",
                "",
            ]
        )
        if schedule:
            out.extend([_ai_footnote(schedule), ""])

    # 人工排程模板（`manual:schedules`）：通用节奏模板，不含官方事实；重渲染按 id 原样回填。
    # 旧实现把它当排程主源（AI 排程永远不渲染），这里降级为缺口补齐前的补充正文。
    default_schedules = (
        "## 通用复习节奏模板（非官方排程）\n\n"
        "| 阶段 | 时间窗 | 任务 | 验收 |\n"
        "| --- | --- | --- | --- |\n"
        "| 建图 | D1-D3 | 核对范围，列章节地图与资料缺口 | 章节地图完成；缺口标明待核验 |\n"
        "| 精读 | D4-D14 | 逐章整理概念、流程、公式或术语 | 每章至少 1 页笔记 |\n"
        "| 刷题 | D15-D22 | 按题型练习并记录错因 | 错题表完成一轮归因 |\n"
        "| 综合 | D23-D27 | 限时做综合练习并订正 | 至少 2 次限时记录 |\n"
        "| 回看 | D28-D30 | 复盘错题与高频点 | 形成考前清单 |\n"
    )
    out.extend([render_manual_block("schedules", default_schedules, manual_blocks), ""])

    out.extend(
        [
            "## 边界",
            "",
            "- 不转载 PDF 原文、截图、第三方题文。",
            "- 未核验考点只进入缺口清单，不写成确定结论。",
            "",
        ]
    )
    return "\n".join(out)


def _render_chapter_page(
    code: str,
    chapter: dict[str, Any],
    blocks_by_point: dict[str, dict[str, dict[str, Any]]],
    manual_blocks: dict[str, str],
    *,
    prev_chapter: dict[str, Any] | None = None,
    next_chapter: dict[str, Any] | None = None,
) -> str:
    title = chapter["title"]

    chapter_nav_items = []
    if prev_chapter:
        prev_fn = f"{prev_chapter['ordinal']:02d}-{prev_chapter['slug']}.md"
        chapter_nav_items.append(f"[← 上一章：{prev_chapter['title']}]({prev_fn})")
    else:
        chapter_nav_items.append("这是第一章")

    chapter_nav_items.append("[返回课程概览](../index.md)")

    if next_chapter:
        next_fn = f"{next_chapter['ordinal']:02d}-{next_chapter['slug']}.md"
        chapter_nav_items.append(f"[下一章：{next_chapter['title']} →]({next_fn})")
    else:
        chapter_nav_items.append("这是最后一章")

    chapter_nav_bar = " ｜ ".join(chapter_nav_items)

    out = [
        GENERATED_COMMENT,
        f"# {title}",
        "",
        AI_BANNER,
        "",
        "[返回课程概览](../index.md) ｜ [学习计划](../plan.md) ｜ [考纲与范围](../syllabus.md) ｜ [练习与真题](../practice.md)",
        "",
        f"**章节导航**：{chapter_nav_bar}",
        "",
        "## 章节概览",
        "",
    ]
    for sec in chapter.get("sections", []):
        out.append(f"- **{sec['title']}**")
    out.extend(
        [
            "",
            "## 官方考核要求",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        out.append(f"### {sec['title']}")
        out.append("")
        out.append("| 知识点编号 | 能力层级 | 考纲原文短语 |")
        out.append("| --- | --- | --- |")
        for p in sec.get("points", []):
            out.append(f"| {p['id']} | {p['requirement']} | {p['quote']} |")
        out.append("")

    if chapter.get("chapter_focus"):
        out.extend(
            [
                "## 本章重点",
                "",
            ]
        )
        for focus in chapter["chapter_focus"]:
            if isinstance(focus, dict):
                text = focus.get("text", "")
                loc = focus.get("locator")
                if loc:
                    out.append(f"- **{text}**（考纲依据：`{loc}`）")
                else:
                    out.append(f"- **{text}**")
            else:
                out.append(f"- {focus}")
        out.append("")

    out.extend(
        [
            "## 核心要点精讲与记忆",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        for p in sec.get("points", []):
            pid = p["id"]
            point_blocks = blocks_by_point.get(pid, {})
            explain = point_blocks.get("explain")
            memorize = point_blocks.get("memorize")
            out.append(f"### 考点精讲：{pid}（{p['requirement']}）")
            out.append("")
            if explain and explain.get("text_md"):
                cleaned_explain = _clean_explain_headings(explain["text_md"].strip())
                out.append(cleaned_explain)
                out.append("")
                out.append(_ai_footnote(explain))
                out.append("")
            if memorize and memorize.get("text_md"):
                out.append("#### 记忆辅助")
                out.append("")
                out.append(memorize["text_md"].strip())
                out.append("")
                out.append(_ai_footnote(memorize))
                out.append("")

    out.extend(
        [
            "## AI 仿真练习题",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        for p in sec.get("points", []):
            pid = p["id"]
            point_blocks = blocks_by_point.get(pid, {})
            drill = point_blocks.get("drill")
            if drill:
                qtype = drill.get("question_type", "题型自测")
                out.append(f"### 练习题：{pid}（{qtype}）")
                out.append("")
                out.append(drill.get("text_md", "").strip())
                out.append("")
                out.append("<details>")
                out.append("<summary>点击查看参考答案与解析</summary>")
                out.append("")
                out.append("**【参考答案与解析】**")
                out.append("")
                out.append(drill.get("answer_md", "").strip())
                out.append("")
                out.append("</details>")
                out.append("")
                out.append(_ai_footnote(drill))
                out.append("")

    out.extend(
        [
            "---",
            "",
            f"**章节导航**：{chapter_nav_bar}",
            "",
        ]
    )

    return "\n".join(out)


def render_course_pages(root: Path, code: str, *, target_dir: Path | None = None) -> list[Path]:
    evidence_path = root / "sources" / "jiangsu" / "courses" / code / "evidence.json"
    model_path = root / "sources" / "jiangsu" / "courses" / code / "knowledge-model.json"
    content_path = root / "sources" / "jiangsu" / "courses" / code / "content.json"

    if not evidence_path.is_file():
        raise FileNotFoundError(f"Missing evidence.json for course {code}")
    if not model_path.is_file():
        raise FileNotFoundError(f"Missing knowledge-model.json for course {code}")
    if not content_path.is_file():
        raise FileNotFoundError(f"Missing content.json for course {code}")

    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    model = json.loads(model_path.read_text(encoding="utf-8"))
    content = json.loads(content_path.read_text(encoding="utf-8"))

    blocks_by_point: dict[str, dict[str, dict[str, Any]]] = {}
    for block in content.get("blocks", []):
        pid = block.get("point_id")
        if not pid:
            continue
        kind = block.get("kind")
        blocks_by_point.setdefault(pid, {})[kind] = block

    out_dir = target_dir or (root / "content" / "jiangsu" / "courses" / code)
    out_dir.mkdir(parents=True, exist_ok=True)
    knowledge_dir = out_dir / "knowledge"
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    repo_course_dir = root / "content" / "jiangsu" / "courses" / code

    def _read_existing(name: str) -> str:
        """既有页面正文（暂存目录优先，其次仓内产物）：渲染必须在其之上增量写，不得整体丢弃手写正文。"""
        t_file = out_dir / name
        if t_file.is_file():
            return t_file.read_text(encoding="utf-8")
        f_file = repo_course_dir / name if repo_course_dir != out_dir else None
        if f_file and f_file.is_file():
            return f_file.read_text(encoding="utf-8")
        return ""

    def _write(name: str, text: str) -> None:
        path = out_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)

    # 1. index.md（官方事实层：正文原样保留 + 派生章链接）
    _write("index.md", _render_index(code, evidence, model, _read_existing("index.md")))

    # 2. syllabus.md（官方事实层）
    _write("syllabus.md", _render_syllabus(code, evidence, model, _read_existing("syllabus.md")))

    # 3. sources.md（官方事实层）
    _write("sources.md", _render_sources(code, evidence, _read_existing("sources.md")))

    # 4. plan.md（AI 备考层：五阶段流程）
    _write("plan.md", _render_plan(code, evidence, model, content))

    # 5. practice.md（AI 备考层：AI 练习题 + 折叠答案）
    _write("practice.md", _render_practice(code, evidence, model, content))

    # 6. review.md（AI 备考层：30/14/7 排程或命名缺口 + manual:schedules 回填）
    rev_text = _read_existing("review.md")
    _write(
        "review.md",
        _render_review(
            code, evidence, model, content, rev_text, get_existing_manual_blocks(out_dir / "review.md", repo_course_dir / "review.md")
        ),
    )

    # 7. 章页（AI 备考层：每章一页）
    chapters = model.get("chapters", [])
    for i, ch in enumerate(chapters):
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        ch_text = _read_existing(f"knowledge/{fname}")
        prev_ch = chapters[i - 1] if i > 0 else None
        next_ch = chapters[i + 1] if i < len(chapters) - 1 else None
        _write(
            f"knowledge/{fname}",
            _render_chapter_page(
                code,
                ch,
                blocks_by_point,
                extract_manual_blocks(ch_text),
                prev_chapter=prev_ch,
                next_chapter=next_ch,
            ),
        )

    return written
