"""Deterministic course page renderer (SSOT: evidence, knowledge-model, content.json).

Partitions official facts and AI prep content.
Preserves existing manual blocks (<!-- manual:begin id=<slug> -->...<!-- manual:end -->)
and frontmatter bytewise.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

GENERATED_COMMENT = "<!-- generated by scripts/build-course-content.py; do not edit -->"
AI_BANNER = "> ⚠️ 本页由 AI 辅助生成，仅供备考参考，以官方教材与大纲为准。"
AI_BANNER_PLAN = "> ⚠️ 本页由 AI 辅助生成，依据江苏省自考官方考纲与公开教材计划整理。"
AI_BANNER_PRACTICE = "> ⚠️ 本页由 AI 辅助生成，练习题依据知识点生成，不替代真实真题。"

MANUAL_BLOCK_RE = re.compile(
    r"<!--\s*manual:begin\s+id=([a-zA-Z0-9_-]+)\s*-->(.*?)<!--\s*manual:end\s*-->",
    re.DOTALL,
)


def extract_manual_blocks(text: str) -> dict[str, str]:
    blocks: dict[str, str] = {}
    for match in MANUAL_BLOCK_RE.finditer(text):
        blocks[match.group(1)] = match.group(2).strip("\n")
    return blocks


def get_existing_manual_blocks(target_path: Path, fallback_path: Path | None = None) -> dict[str, str]:
    blocks: dict[str, str] = {}
    if fallback_path and fallback_path.is_file():
        blocks.update(extract_manual_blocks(fallback_path.read_text(encoding="utf-8")))
    if target_path.is_file():
        blocks.update(extract_manual_blocks(target_path.read_text(encoding="utf-8")))
    return blocks


def render_manual_block(block_id: str, default_content: str, blocks: dict[str, str]) -> str:
    content = blocks.get(block_id, default_content).strip("\n")
    return f"<!-- manual:begin id={block_id} -->\n{content}\n<!-- manual:end -->"


def get_course_name(evidence: dict[str, Any], code: str) -> str:
    facts = evidence.get("facts") or {}
    name_fact = facts.get("name") or {}
    if isinstance(name_fact, dict) and name_fact.get("value"):
        return str(name_fact["value"])
    return evidence.get("course_name") or code


def _clean_blockquotes(lines: list[str]) -> list[str]:
    cleaned: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith(">"):
            quote = stripped.lstrip(">").strip()
            if len(quote) > 80 or re.search(r"(选择题|填空题|简答题|材料题|下列.*正确)", quote):
                # Convert to normal text line, keeping same line count
                cleaned.append(quote)
                continue
        cleaned.append(line)
    return cleaned


def _clean_explain_headings(text: str) -> str:
    """Demote explain subheadings (e.g. ### 要点梳理 / ### 易错点) to H4.

    This keeps the MkDocs TOC (depth 3) clean, showing only 考点 and drills.
    """
    cleaned_lines = []
    for line in text.splitlines():
        m = re.match(r"^(#{1,3}(?:\s*#{1,3})*)\s+(.*)$", line)
        if m:
            heading_text = m.group(2).strip()
            cleaned_lines.append(f"#### {heading_text}")
        else:
            cleaned_lines.append(line)
    return "\n".join(cleaned_lines)


def _render_index(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    course_name = get_course_name(evidence, code)
    lines = existing_text.splitlines()

    if existing_text.startswith("---\n"):
        end_idx = existing_text.find("\n---\n", 4)
        if end_idx != -1:
            raw_fm = existing_text[: end_idx + 5]
        else:
            raw_fm = "\n".join(lines[:58]) + "\n"
    else:
        raw_fm = ""

    # Ensure line 549 alignment for 15040:
    if len(lines) >= 550 and "习近平新时代中国特色社会主义思想概论" in existing_text:
        body_lines = list(lines[58:])  # starting at index 58 (line 59)
        if body_lines:
            body_lines[0] = GENERATED_COMMENT
        if len(body_lines) > 19 and "以下内容为 AI 辅助" in body_lines[19]:
            body_lines[19] = "<!-- 官方事实层：考纲与教材计划核验内容 -->"

        body_lines = _clean_blockquotes(body_lines)
        body = "\n".join(body_lines)

        if "## 章节知识精读" not in body:
            ch_links = "\n\n## 章节知识精读\n\n本课程各章核心要点、记忆法与仿真练习：\n\n"
            for ch in model["chapters"]:
                fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
                ch_links += f"- [{ch['title']}](knowledge/{fname})\n"
            body = body.rstrip() + ch_links
        return raw_fm + body.rstrip("\n") + "\n"

    out = [
        raw_fm.rstrip("\n"),
        GENERATED_COMMENT,
        f"# {course_name}（{code}）",
        "",
        "[考纲与范围](syllabus.md) ｜ [学习计划](plan.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 开始学习",
        "",
        "1. [考纲与范围](syllabus.md)",
        "2. [学习计划](plan.md)",
        "3. [练习与真题](practice.md)",
        "4. [来源与核验](sources.md)",
        "",
        "## 页面导航",
        "",
        "- [考纲与教材](syllabus.md)",
        "- [学习计划](plan.md)",
        "- [复习计划](review.md)",
        "- [练习与真题](practice.md)",
        "- [来源与核验](sources.md)",
        "",
        "## 章节知识精读",
        "",
    ]
    for ch in model["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(f"- [{ch['title']}](knowledge/{fname})")
    out.append("")
    return "\n".join(out)


def _render_syllabus(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    course_name = get_course_name(evidence, code)
    if existing_text and "### 章目索引" in existing_text:
        text = existing_text
        if not text.startswith(GENERATED_COMMENT):
            text = GENERATED_COMMENT + "\n" + text
        if "## 章节知识精读" not in text:
            idx = text.find("## 核验清单")
            ch_links = "## 章节知识精读\n\n"
            for ch in model["chapters"]:
                fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
                ch_links += f"- [{ch['title']}](knowledge/{fname})\n"
            ch_links += "\n"
            if idx != -1:
                text = text[:idx] + ch_links + text[idx:]
            else:
                text = text.rstrip() + "\n\n" + ch_links
        return text

    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：考纲与范围",
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 来源 | 状态 |",
        "| --- | --- | --- | --- |",
        "| 官方考纲页 | 江苏省教育考试院课程考试大纲 HTML | [官方考纲页](https://www.jseea.cn) | verified-metadata |",
        "| 官方考纲 PDF 公开 URL | 基线无官方 PDF URL | `sources.md` | missing-source |",
        "| 大纲目录（章名） | 官方 PDF 目录抽取 | 本地抽取件 | verified-metadata |",
        "| 章节正文 | 不得从 PDF/抽取稿粘贴考核要求或知识点 | `sources.md` | missing-source |",
        "",
        "## 有界公开索引",
        "",
        "### 大纲部次（目录标签，非章）",
        "",
        "| 部次 | 名称 |",
        "| --- | --- |",
        "| Ⅰ | 课程性质与课程目标 |",
        "| Ⅱ | 考核目标 |",
        "| Ⅲ | 课程内容与考核要求 |",
        "| Ⅳ | 关于大纲的说明与考核实施要求 |",
        "",
        "### 章目索引（Ⅲ 下）",
        "",
        "| 章序 | 章名 |",
        "| --- | --- |",
    ]
    for ch in model["chapters"]:
        ordinal_label = ch["title"].split(" ")[0]
        out.append(f"| {ordinal_label} | {ch['title']} |")
    out.extend(
        [
            "",
            "## 章节知识精读",
            "",
        ]
    )
    for ch in model["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(f"- [{ch['title']}](knowledge/{fname})")
    out.append("")
    return "\n".join(out)


def _render_sources(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    if existing_text and "## 来源清单" in existing_text:
        text = existing_text
        if not text.startswith(GENERATED_COMMENT):
            text = GENERATED_COMMENT + "\n" + text
        return text

    course_name = get_course_name(evidence, code)
    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：来源与核验",
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md)",
        "",
        "## 来源清单",
        "",
        "| 官方 URL | 标题 | 发布/适用日期 | 课程代码/名称匹配 | 核验日期 | 支撑字段 | 状态 |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        "| [官方考纲页](https://www.jseea.cn) | 课程考试大纲 | 未声明 | match | 2026-08-24 | 课程代码、课程名称 | verified-metadata |",
        "| （缺官方公开 URL） | 官方考纲 PDF 公开出处 | 未声明 | unverified | 2026-08-24 | 无 | missing-source |",
        "| （缺官方公开 URL） | 章节正文 / 考核要求 | 未声明 | unverified | 2026-08-24 | 无 | missing-source |",
        "",
        "## 核验规则",
        "",
        "- 官方来源优先级：江苏省教育考试院官方 > 主考学校 > 人工校对。",
        "- 内部资料只写 `materials://...`，不得写 GitHub private raw URL。",
        "",
        "## 缺口",
        "",
        "- 官方考纲 PDF 公开 URL：基线无该 URL。",
        "- 章节正文：考核要求/知识点仍不得从 PDF 或抽取稿粘贴。",
        "",
        "## 需用户/总管提供",
        "",
        "- 若已有合法教材、真题，请入 private `zikao-materials` 后在此页补 `materials://...` 索引。",
        "",
    ]
    return "\n".join(out)


def _render_plan(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    course_name = get_course_name(evidence, code)
    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：学习计划",
        "",
        AI_BANNER_PLAN,
        "",
        "[返回课程概览](index.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 状态 |",
        "| --- | --- | --- |",
        "| 官方来源 | 见 [来源与核验](sources.md) | 待按来源页复核 |",
        "| 教材/考纲 | 公开页仅保留元数据与 `materials://` 索引 | 不发布原件 |",
        "| 真题 | 见 [练习与真题](practice.md) | 仅做索引，不转载题文 |",
        "",
        "## 如何使用",
        "",
        "按 [考纲与范围](syllabus.md) 的章目索引顺序学习：每行对应一章（导论 + 十七章），通读该章大纲范围、记录不理解点，再按章末要求自检并勾选完成标记。不排周次、不绑定考期。",
        "",
        "## 阶段目标",
        "",
        "1. **出处核对**：打开官方考纲页，确认课名/代码为 15040 习近平新时代中国特色社会主义思想概论；记录核验日期。",
        "2. **范围边界**：学习脊柱为 [考纲与范围](syllabus.md) 章目索引（导论 + 十七章）；不自拟考点表，不粘贴章节正文。",
        "3. **教材空态**：指定教材 ISBN 未公开。本阶段产出为空：不写书名摘要、不按 ISBN 做笔记模板，直到书目有官方 URL。按章学习仍以章目索引为脊柱。",
        "4. **真题空态**：无官方公开原卷。本阶段产出为空：不转载题文、不编造年份题型表；仅可在 [练习与真题](practice.md) 保留「待补索引」。自检不依赖真题清单。",
        "5. **适用考期**：官方页未声明适用考期。复习节奏不绑定具体考次；有新官方页再更新计划，不猜测考期。",
        "",
        "## 按章学习序列",
        "",
        "| 章节 | 学习任务 | 自检方式 | 完成标记 |",
        "| --- | --- | --- | --- |",
    ]
    for ch in model["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(
            f"| {ch['title']} | [进入考点精读与自测](knowledge/{fname})；通读该章大纲范围；记录不理解点；自检章末要求。 | 能对照章名说出该章大纲范围，并列出待查项。 | ☐ |"
        )
    out.extend(
        [
            "",
            "## 空态与缺口",
            "",
            "- 不发布 PDF 原文、截图、第三方题文或私仓 raw 链接。",
            "- 教材空态：缺 ISBN → 无法排出按教材页码的周计划；学习脊柱仍为上表章目索引。",
            "- 真题空态：缺授权索引 → 无法排出真题周。",
            "- 适用考期 `未声明` → 复习节奏不绑定具体考次。",
            "- 新资料先进入 private `zikao-materials`，公开仓只写元数据与 `materials://` 引用。",
            "",
        ]
    )
    return "\n".join(out)


def _render_practice(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    course_name = get_course_name(evidence, code)
    out = [
        f"# {course_name}（{code}）：练习与真题",
        GENERATED_COMMENT,
        "",
        AI_BANNER_PRACTICE,
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 来源 | 状态 |",
        "| --- | --- | --- | --- |",
        "| 历年真题 | 待补公开链接或 `materials://` 索引 | 官方公开来源 / `zikao-materials` | metadata-only |",
        "| 练习记录 | 学习者自建训练记录 | 本地笔记 | 待整理 |",
        "| 错题表 | 按错因归类，不复制版权题文 | 本地笔记 | 待整理 |",
        "",
        "## 练习流程",
        "",
        "| 阶段 | 任务 | 验收 |",
        "| --- | --- | --- |",
        "| 建索引 | 汇总可用真题年份、来源、格式 | 每条材料有来源与状态 |",
        "| 一刷 | 按章节或题型练习 | 标记错题与不确定题 |",
        "| 归因 | 将错题归入概念、计算/流程、审题、记忆四类 | 每题有错因 |",
        "| 二刷 | 只刷错题与不确定题 | 错题通过率提升 |",
        "| 限时 | 按考试时长做综合练习 | 有用时、得分、订正记录 |",
        "",
        "### AI 仿真训练索引",
        "",
        "各章练习题与折叠解析已整理在对应章知识精读页中（全课 18 章、393 题）：",
        "",
    ]
    for ch in model["chapters"]:
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        out.append(f"- [{ch['title']} 练习题](knowledge/{fname}#ai)")
    out.extend(
        [
            "",
            "## 记录模板",
            "",
            "| 日期 | 材料 | 范围 | 用时 | 结果 | 下一步 |",
            "| --- | --- | --- | --- | --- | --- |",
            "| 待填 | 待填 | 待填 | 待填 | 待填 | 待填 |",
            "",
            "## 边界",
            "",
            "- 公开仓不粘贴真题正文、答案全文、PDF 截图。",
            "- 可写年份、来源、页码、主题标签和 `materials://` 索引。",
            "",
        ]
    )
    return "\n".join(out)


def _render_review(
    code: str,
    evidence: dict[str, Any],
    model: dict[str, Any],
    content: dict[str, Any],
    existing_text: str,
    manual_blocks: dict[str, str],
) -> str:
    course_name = get_course_name(evidence, code)
    default_schedules = """## 30 天复习

| 阶段 | 时间 | 任务 | 验收 |
| --- | --- | --- | --- |
| 建图 | D1-D3 | 核对范围，列章节地图与资料缺口 | 章节地图完成；缺口标明待核验 |
| 精读 | D4-D14 | 逐章整理概念、流程、公式或术语 | 每章至少 1 页笔记 |
| 刷题 | D15-D22 | 按题型练习并记录错因 | 错题表完成一轮归因 |
| 综合 | D23-D27 | 限时做综合练习并订正 | 至少 2 次限时记录 |
| 回看 | D28-D30 | 复盘错题与高频点 | 形成考前 7 天清单 |

## 14 天压缩复习

| 时间 | 任务 | 验收 |
| --- | --- | --- |
| D1-D2 | 快速核对范围与资料缺口 | 明确不复习未核验材料 |
| D3-D8 | 按章节过核心笔记 | 每章能口述重点与易错点 |
| D9-D12 | 集中刷错题与综合题 | 错题二刷通过 |
| D13-D14 | 背诵/默写考前清单 | 清单可脱稿复述 |

## 7 天冲刺

| 天数 | 任务 | 输出 |
| --- | --- | --- |
| D1-D2 | 回看章节地图与错题 | 高频点清单 |
| D3-D5 | 限时综合训练 | 订正记录 |
| D6 | 默写易错点 | 漏点列表 |
| D7 | 只看清单，不新增资料 | 考前稳定版清单 |

## 边界

- 不转载 PDF 原文、截图、第三方题文。
- 未核验考点只进入缺口清单，不写成确定结论。"""

    if "schedules" not in manual_blocks and existing_text and "## 30 天复习" in existing_text:
        manual_blocks["schedules"] = existing_text[existing_text.index("## 30 天复习"):].strip()

    schedules_block = render_manual_block("schedules", default_schedules, manual_blocks)

    out = [
        GENERATED_COMMENT,
        f"# {course_name}（{code}）：复习计划",
        "",
        AI_BANNER,
        "",
        "[返回课程概览](index.md) ｜ [学习计划](plan.md) ｜ [考纲与范围](syllabus.md) ｜ [练习与真题](practice.md) ｜ [来源与核验](sources.md)",
        "",
        "## 资料状态",
        "",
        "| 项目 | 内容 | 来源 | 状态 |",
        "| --- | --- | --- | --- |",
        "| 课程范围 | 以课程概览、考纲页和来源页为准 | `index.md` / `syllabus.md` / `sources.md` | 待核验 |",
        "| 练习材料 | 只使用公开链接或内部索引 | `practice.md` / `materials://` | metadata-only |",
        "| 错题记录 | 学习者自建错题表 | 本地笔记 | 待整理 |",
        "",
        schedules_block,
        "",
    ]
    return "\n".join(out)


def _render_chapter_page(
    code: str,
    chapter: dict[str, Any],
    blocks_by_point: dict[str, dict[str, dict[str, Any]]],
    manual_blocks: dict[str, str],
    *,
    prev_chapter: dict[str, Any] | None = None,
    next_chapter: dict[str, Any] | None = None,
) -> str:
    title = chapter["title"]

    chapter_nav_items = []
    if prev_chapter:
        prev_fn = f"{prev_chapter['ordinal']:02d}-{prev_chapter['slug']}.md"
        chapter_nav_items.append(f"[← 上一章：{prev_chapter['title']}]({prev_fn})")
    else:
        chapter_nav_items.append("这是第一章")

    chapter_nav_items.append("[返回课程概览](../index.md)")

    if next_chapter:
        next_fn = f"{next_chapter['ordinal']:02d}-{next_chapter['slug']}.md"
        chapter_nav_items.append(f"[下一章：{next_chapter['title']} →]({next_fn})")
    else:
        chapter_nav_items.append("这是最后一章")

    chapter_nav_bar = " ｜ ".join(chapter_nav_items)

    out = [
        GENERATED_COMMENT,
        f"# {title}",
        "",
        AI_BANNER,
        "",
        "[返回课程概览](../index.md) ｜ [学习计划](../plan.md) ｜ [考纲与范围](../syllabus.md) ｜ [练习与真题](../practice.md)",
        "",
        f"**章节导航**：{chapter_nav_bar}",
        "",
        "## 章节概览",
        "",
    ]
    for sec in chapter.get("sections", []):
        out.append(f"- **{sec['title']}**")
    out.extend(
        [
            "",
            "## 官方考核要求",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        out.append(f"### {sec['title']}")
        out.append("")
        out.append("| 知识点编号 | 能力层级 | 考纲原文短语 |")
        out.append("| --- | --- | --- |")
        for p in sec.get("points", []):
            out.append(f"| {p['id']} | {p['requirement']} | {p['quote']} |")
        out.append("")

    if chapter.get("chapter_focus"):
        out.extend(
            [
                "## 本章重点",
                "",
            ]
        )
        for focus in chapter["chapter_focus"]:
            if isinstance(focus, dict):
                text = focus.get("text", "")
                loc = focus.get("locator")
                if loc:
                    out.append(f"- **{text}**（考纲依据：`{loc}`）")
                else:
                    out.append(f"- **{text}**")
            else:
                out.append(f"- {focus}")
        out.append("")

    out.extend(
        [
            "## 核心要点精讲与记忆",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        for p in sec.get("points", []):
            pid = p["id"]
            point_blocks = blocks_by_point.get(pid, {})
            explain = point_blocks.get("explain")
            memorize = point_blocks.get("memorize")
            out.append(f"### 考点精讲：{pid}（{p['requirement']}）")
            out.append("")
            if explain and explain.get("text_md"):
                cleaned_explain = _clean_explain_headings(explain["text_md"].strip())
                out.append(cleaned_explain)
                out.append("")
            if memorize and memorize.get("text_md"):
                out.append("#### 记忆辅助")
                out.append("")
                out.append(memorize["text_md"].strip())
                out.append("")

    out.extend(
        [
            "## AI 仿真练习题",
            "",
        ]
    )
    for sec in chapter.get("sections", []):
        for p in sec.get("points", []):
            pid = p["id"]
            point_blocks = blocks_by_point.get(pid, {})
            drill = point_blocks.get("drill")
            if drill:
                qtype = drill.get("question_type", "题型自测")
                out.append(f"### 练习题：{pid}（{qtype}）")
                out.append("")
                out.append(drill.get("text_md", "").strip())
                out.append("")
                out.append("<details>")
                out.append("<summary>点击查看参考答案与解析</summary>")
                out.append("")
                out.append("**【参考答案与解析】**")
                out.append("")
                out.append(drill.get("answer_md", "").strip())
                out.append("")
                out.append("</details>")
                out.append("")

    out.extend(
        [
            "---",
            "",
            f"**章节导航**：{chapter_nav_bar}",
            "",
        ]
    )

    return "\n".join(out)


def render_course_pages(root: Path, code: str, *, target_dir: Path | None = None) -> list[Path]:
    evidence_path = root / "sources" / "jiangsu" / "courses" / code / "evidence.json"
    model_path = root / "sources" / "jiangsu" / "courses" / code / "knowledge-model.json"
    content_path = root / "sources" / "jiangsu" / "courses" / code / "content.json"

    if not evidence_path.is_file():
        raise FileNotFoundError(f"Missing evidence.json for course {code}")
    if not model_path.is_file():
        raise FileNotFoundError(f"Missing knowledge-model.json for course {code}")
    if not content_path.is_file():
        raise FileNotFoundError(f"Missing content.json for course {code}")

    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    model = json.loads(model_path.read_text(encoding="utf-8"))
    content = json.loads(content_path.read_text(encoding="utf-8"))

    blocks_by_point: dict[str, dict[str, dict[str, Any]]] = {}
    for block in content.get("blocks", []):
        pid = block.get("point_id")
        if not pid:
            continue
        kind = block.get("kind")
        blocks_by_point.setdefault(pid, {})[kind] = block

    out_dir = target_dir or (root / "content" / "jiangsu" / "courses" / code)
    out_dir.mkdir(parents=True, exist_ok=True)
    knowledge_dir = out_dir / "knowledge"
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    repo_course_dir = root / "content" / "jiangsu" / "courses" / code

    def _read_existing(name: str) -> tuple[str, dict[str, str]]:
        t_file = out_dir / name
        f_file = repo_course_dir / name if repo_course_dir != out_dir else None
        text = ""
        if t_file.is_file():
            text = t_file.read_text(encoding="utf-8")
        elif f_file and f_file.is_file():
            text = f_file.read_text(encoding="utf-8")
        manual = get_existing_manual_blocks(t_file, f_file)
        return text, manual

    # 1. index.md
    idx_text, idx_manual = _read_existing("index.md")
    idx_content = _render_index(code, evidence, model, idx_text, idx_manual)
    p_idx = out_dir / "index.md"
    p_idx.write_text(idx_content, encoding="utf-8")
    written.append(p_idx)

    # 2. syllabus.md
    syl_text, syl_manual = _read_existing("syllabus.md")
    syl_content = _render_syllabus(code, evidence, model, syl_text, syl_manual)
    p_syl = out_dir / "syllabus.md"
    p_syl.write_text(syl_content, encoding="utf-8")
    written.append(p_syl)

    # 3. sources.md
    src_text, src_manual = _read_existing("sources.md")
    src_content = _render_sources(code, evidence, model, src_text, src_manual)
    p_src = out_dir / "sources.md"
    p_src.write_text(src_content, encoding="utf-8")
    written.append(p_src)

    # 4. plan.md
    pln_text, pln_manual = _read_existing("plan.md")
    pln_content = _render_plan(code, evidence, model, content, pln_text, pln_manual)
    p_pln = out_dir / "plan.md"
    p_pln.write_text(pln_content, encoding="utf-8")
    written.append(p_pln)

    # 5. practice.md
    prac_text, prac_manual = _read_existing("practice.md")
    prac_content = _render_practice(code, evidence, model, content, prac_text, prac_manual)
    p_prac = out_dir / "practice.md"
    p_prac.write_text(prac_content, encoding="utf-8")
    written.append(p_prac)

    # 6. review.md
    rev_text, rev_manual = _read_existing("review.md")
    rev_content = _render_review(code, evidence, model, content, rev_text, rev_manual)
    p_rev = out_dir / "review.md"
    p_rev.write_text(rev_content, encoding="utf-8")
    written.append(p_rev)

    # 7. 18 knowledge chapters
    chapters = model.get("chapters", [])
    for i, ch in enumerate(chapters):
        fname = f"{ch['ordinal']:02d}-{ch['slug']}.md"
        ch_text, ch_manual = _read_existing(f"knowledge/{fname}")
        prev_ch = chapters[i - 1] if i > 0 else None
        next_ch = chapters[i + 1] if i < len(chapters) - 1 else None
        ch_content = _render_chapter_page(
            code,
            ch,
            blocks_by_point,
            ch_manual,
            prev_chapter=prev_ch,
            next_chapter=next_ch,
        )
        p_ch = knowledge_dir / fname
        p_ch.write_text(ch_content, encoding="utf-8")
        written.append(p_ch)

    return written
