"""AI Content Gate: validates AI prep layer contracts (Issue #55 / Task 6).

覆盖对象 = **存在 `content.json` 的课程**（作用域规则：新层只对存在产物的课程生效，
其余 17 门课保持全绿）。四类校验：

1. **标注四件套**（`validate_content_doc`）：`blocks[]` / `stage_plan[]` / `review_schedule` 及其 `plans[]`；
2. **8-gram 抄袭守卫**：语料取自 `evidence.json` 的 `syllabus.path`，并**校验 `sha256`**（QC1 F-5：
   旧实现按目录 glob 找语料、空即**静默跳过**，等于把闸门交给文件命名）；
3. **页面标记**：页面分类与标记字符串一律取自 `course.schema.json` 的 `generated_page_markers`
   （QC1 F-4 / QC3-003：schema 是唯一真源，同一规则不写两遍）；
4. **AI 块必须真正落到页面**（QC3-001 / C2-004 / W1 / B2a N-1 / F-QC2-1）：对账口径 = **4 个 block kind
   （`explain` / `memorize` / `drill` / `exam_strategy`）+ 2 个课程级顶层产物（`stage_plan` /
   `review_schedule`）**：`explain` / `memorize` 按**逐考核点锚点**对账（`### 考点精讲：<point_id>`
   小节内必须有对应 H4 小节），并保留全局小节计数（精确相等）作次级页级界限；`practice.md` 的 drill 数、
   `plan.md` 的五阶段与 `## 应试策略`、`review.md` 的排程，逐项与 `content.json` 对账；
   课程存在 `content.json` 而渲染页目录不存在时**失败关闭**，不静默跳过整门课。
   这一条缺失正是「AI 备考层从未被渲染」能过关的原因：先只覆盖 3/4 个 kind（`exam_strategy` 整块删掉仍两层全绿），
   后又是 `explain` / `memorize` 无对账 + 目录缺失静默 `continue`。

`rendered_course_dir` / `course_code` 让 `build` 的 `gate` 阶段校验**暂存区**页面而不是仓内既有页面。
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from lib import course_pages_contract
from lib.course_pipeline.generate_content import (
    plagiarism_violations,
    validate_content_doc,
)

# 8-gram 之外的文本边界（plan § Data contracts 5 / design-notes §2 invariant 5）：`>` 引用块 ≤ 80 字符。
MAX_BLOCKQUOTE_CHARS = 80
QUESTION_TEXT_RE = re.compile(r"(选择题|填空题|简答题|材料题|下列.*正确)")

# `explain` / `memorize` 的唯一落点 = 渲染器的章页（`out_dir/knowledge/<NN>-<slug>.md`：
# `render_pages.py:881-882` 建目录、`:927-936` 逐章写入）。两个小节标题是**契约字面量**：
# `#### 记忆辅助` 由渲染器产出（`:807`）；`#### 要点梳理` 来自提示词常量
# （`generate_content.py:54` 的 `EXPLAIN_SUMMARY_HEADING`，由 `validate_content_doc()` 强制每个 explain
# 块必含），经 `_clean_explain_headings()`（`:141-155`）由 H3 降为 H4。计数一律按 H4 精确整行。
CHAPTER_PAGE_PATTERN = "knowledge/*.md"
EXPLAIN_SUMMARY_RE = re.compile(r"(?m)^#### 要点梳理$")
MEMORIZE_AID_RE = re.compile(r"(?m)^#### 记忆辅助$")

# `explain` / `memorize` 的**逐考核点**锚点：渲染器在 `### 考点精讲：{point_id}（{requirement}）`
# 之下、紧挨着写出 explain 正文（`#### 要点梳理` 为其中一节）与 memorize 正文（`#### 记忆辅助`），
# 见 `render_pages.py:798-809`。H3 切分（`^### `）与 `drill` 的 `^### ` 小节口径一致；
# 该锚点同时是 MkDocs 目录里的稳定定位符，随页面重建而重建。
ANCHOR_SPLIT_RE = re.compile(r"(?m)^### ")
POINT_ANCHOR_RE = re.compile(r"^### 考点精讲：(?P<point_id>[^\s（]+)（")


def _syllabus_text(root: Path, code: str, rel_content: str, errors: list[str]) -> str:
    """考纲语料 = `evidence.json.syllabus.path` 的内容，且 `sha256` 必须与记录一致（缺失即失败关闭）。"""
    evidence_path = root / "sources" / "jiangsu" / "courses" / code / "evidence.json"
    if not evidence_path.is_file():
        errors.append(f"course {code}: content.json 存在但 evidence.json 缺失（无考纲语料可校验）")
        return ""
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    syllabus = evidence.get("syllabus") or {}
    rel_path = syllabus.get("path")
    if syllabus.get("status") != "extracted" or not rel_path:
        errors.append(f"course {code}: 考纲未 extracted（{rel_content} 的 8-gram 语料缺失，禁止静默跳过）")
        return ""
    document = root / rel_path
    if not document.is_file():
        errors.append(f"course {code}: evidence.json 指向的考纲抽取件不存在: {rel_path}")
        return ""
    recorded = syllabus.get("sha256")
    actual = hashlib.sha256(document.read_bytes()).hexdigest()
    if recorded != actual:
        errors.append(f"course {code}: 考纲抽取件 sha256 与 evidence.json 不一致（{rel_path}）")
        return ""
    return document.read_text(encoding="utf-8")


def _page_problems(rel_md: str, text: str, markers: dict, errors: list[str], *, label: str | None = None) -> None:
    """单页标记与文本边界（横幅双向断言 + generated 注释 + 生成页的引用块上限）。

    引用块上限只作用于**渲染器产出**的页面：`official_only` 页面（`index.md` / `syllabus.md` /
    `sources.md`）的正文是手写官方事实页，渲染器不得改写（QC3-002 / QC3-006 / C2-011）。
    对它们套用「≤ 80 字符」等于要求「删掉手写正文的引用块」，而那正是被判定的 Critical 缺陷本身。

    `rel_md` 是相对课程目录的路径（页面分类用），`label` 是报错前缀。
    """
    where = label or rel_md
    if markers["any"] not in text:
        errors.append(f"{where}: 缺少生成标识注释 <!-- generated by ... -->")

    is_official = course_pages_contract.matches_page(rel_md, markers["official_only"])
    is_ai = course_pages_contract.matches_page(rel_md, markers["ai_pages"])
    if is_official and markers["ai_banner"] in text:
        errors.append(f"{where}: 官方页面意外包含 AI 横幅 banner（{markers['ai_banner']}）")
    elif is_ai and markers["ai_banner"] not in text:
        errors.append(f"{where}: AI 页面缺少 AI 横幅 banner（{markers['ai_banner']}）")

    if is_official:
        return
    for line in text.splitlines():
        stripped = line.lstrip()
        if not stripped.startswith(">"):
            continue
        quote = stripped.lstrip(">").strip()
        if len(quote) > MAX_BLOCKQUOTE_CHARS:
            errors.append(f"{where}: 引用块超过 {MAX_BLOCKQUOTE_CHARS} 字符（{len(quote)}）: {quote[:40]}...")
        if QUESTION_TEXT_RE.search(quote):
            errors.append(f"{where}: 引用块出现题文特征: {quote[:40]}...")


def _chapter_page_sections(page_text: dict[str, str]) -> tuple[str, dict[str, str]]:
    """章页正文拼接 + `### 考点精讲：<point_id>` 锚点小节索引（H4 标题留在自己的小节内）。

    以 `^### ` 切分：章页上每个 H3 都是渲染器的**契约标题**（`### {章标题}` / `### 考点精讲：<point_id>`
    / `### 练习题：<point_id>`，见 `render_pages.py:798,827`），H4 小节因而必定落在其所属锚点小节之内。
    页面顺序在两门课内**唯一**（`render_pages.py:881-882,927-936` 逐章写一个文件）；真出现重复时后者覆盖
    前者，`rendered != expected` 的页级计数会兜住。
    """
    chapters: list[str] = []
    sections: dict[str, str] = {}
    for rel_md, text in page_text.items():
        if not course_pages_contract.matches_page(rel_md, {CHAPTER_PAGE_PATTERN}):
            continue
        chapters.append(text)
        # `split` 无捕获组：`parts[0]` 是页面前言，`parts[1:]` 每项 = 一个 H3 的标题行 + 其正文，
        # 正好一节；不能再两两配对（那会把相邻小节拼进来 —— 邻节的 H4 会掩盖本节的缺失）。
        for chunk in ANCHOR_SPLIT_RE.split(text)[1:]:
            section = "### " + chunk
            match = POINT_ANCHOR_RE.match(section)
            if match:
                sections[match.group("point_id")] = section
    return "".join(chapters), sections


def _per_point_reached_problems(
    code: str, content: dict, sections: dict[str, str], errors: list[str]
) -> None:
    """逐 `point_id` 对账：块是「真值」，它指名的考核点必须在章页上**有自己那一节**（F-QC2-1）。

    口径 = 锚点小节**内**的 H4 小节：`explain` 块要求 `### 考点精讲：<point_id>` 小节内出现
    `^#### 要点梳理$`；`memorize` 块要求同一小节内出现 `^#### 记忆辅助$`。因此
    「删掉某点的整节、再在别处补一条同名标题」不再能蒙混过关（全局计数不变、相邻小节的同名 H4 也不会
    被误算进来，但该 `point_id` 的锚点/小节确实没了），错误文案**点名缺失的 `point_id`**，
    与 `drill` 的锚点对账（`practice.md`）同一形态。
    调用顺序上逐点在前、全局计数在后：计数不匹配只是次级「页级界限」，块级真相优先（否则「丢一节 + 别处补一条」
    只会报成模糊的计数不符）。有块却无锚点的考核点算失败；没有块的考核点不在此列（无块即无诉求）。
    """
    for kind, heading_re, heading in (
        ("explain", EXPLAIN_SUMMARY_RE, "要点梳理"),
        ("memorize", MEMORIZE_AID_RE, "记忆辅助"),
    ):
        block_points = [
            str(block["point_id"])
            for block in content.get("blocks") or []
            if block.get("kind") == kind and block.get("point_id")
        ]
        missing_anchor: list[str] = []
        missing_heading: list[str] = []
        for point_id in block_points:
            section = sections.get(point_id)
            if section is None:
                missing_anchor.append(point_id)
            elif not heading_re.search(section):
                missing_heading.append(point_id)
        if missing_anchor:
            errors.append(
                f"course {code}: 章页缺少 {len(missing_anchor)} 个考核点的 `### 考点精讲：<point_id>` 锚点"
                f"（首个 {missing_anchor[0]}）—— 该 point_id 的 {kind} 块未渲染到章页"
            )
        if missing_heading:
            errors.append(
                f"course {code}: 章页有 {len(missing_heading)} 个考核点的锚点小节内缺少 `#### {heading}`"
                f"（首个 {missing_heading[0]}）—— 该 point_id 的 {kind} 块未渲染到章页"
            )


def _page_reached_problems(code: str, content: dict, page_text: dict[str, str], errors: list[str]) -> None:
    """每个 AI 产物块都必须真的落到页面上（QC3-001 / C2-004 / W1 / B2a N-1：闸门只看页面装饰，看不出整层丢失）。

    对账口径按 kind —— **4 个 block kind + 2 个课程级顶层产物，一个都不能漏**：
    - `explain` → 全局章页内 `^#### 要点梳理$` 计数**精确等于**块数（次级页级界限），
      **且**逐 `point_id`：该点在章页上有 `### 考点精讲：<point_id>` 锚点，且锚点小节内有 `#### 要点梳理`；
    - `memorize` → 全局 `^#### 记忆辅助$` 计数**精确等于**块数（次级页级界限），**且**同样的逐点锚点口径；
    - `drill` → `practice.md` 的 `###` 小节数 + 逐 `point_id` 的练习小节锚点；
    - `stage_plan[]`（恰 5 条）→ `plan.md` 逐阶段名 + `done_when`；
    - `exam_strategy`（课程级块）→ `plan.md` 的 `## 应试策略` 区块内的 `text_md`；
    - `review_schedule` → `review.md` 的三档排程或命名缺口。

    `exam_strategy` 这一条是 W1：它曾经既不在渲染器里、也不在本函数里，于是删掉整块
    （1180 → 1179）两层闸门全绿。`explain` / `memorize` 是 B2a 的 N-1：两者有写入者（章页）却无对账，
    于是删掉章页的 `#### 要点梳理` + `#### 记忆辅助`、乃至删掉整个 `knowledge/` 目录都仍然全绿。
    主判据因此是**逐点锚点**（`_per_point_reached_problems`）：块是「真值」，每个有块的 `point_id` 都要在
    章页上存在自己的 `### 考点精讲：<point_id>` 小节，且该小节内有对应 H4 标题；错误文案点名缺失的
    `point_id`，与 `drill` 的锚点对账同一形态。注意 F-QC2-1：**精确计数并不能防住 padding** ——
    删掉 `15043-ch01-s1-p1` 的 `#### 要点梳理` 小节、再在别的章页补一条同名标题，255 == 255 依旧全绿，
    因为全局计数只回答「渲染了几个」，回答不了「渲染了哪几个」；`drill` 那样的下界（`rendered < len(drills)`）
    同理。所以计数降级为**次级页级界限**（总量兜底：整页/整目录级丢失、以及多写一条标题），
    逐点锚点才是主判据。`blocks[]` 里没有写入者的 kind 由
    `validate_content_doc()`（`BLOCK_KINDS` 枚举）拦下，所以这里只需覆盖「有写入者的 kind」。
    """
    chapters_text, sections = _chapter_page_sections(page_text)

    # 主判据：逐考核点（F-QC2-1 —— 能点名是哪个 point_id 丢了）。
    _per_point_reached_problems(code, content, sections, errors)

    # 次级界限：全局小节计数精确相等（页级总量兜底，message 措辞保持稳定以兼容既有测试）。
    for kind, heading_re, heading in (
        ("explain", EXPLAIN_SUMMARY_RE, "要点梳理"),
        ("memorize", MEMORIZE_AID_RE, "记忆辅助"),
    ):
        expected = len([b for b in content.get("blocks") or [] if b.get("kind") == kind])
        rendered = len(heading_re.findall(chapters_text))
        if rendered != expected:
            errors.append(
                f"course {code}: 章页的 `#### {heading}` 小节数 {rendered} 与 content.json 的 {kind} 块数 {expected} "
                f"不一致（{kind} 块未渲染到章页）"
            )

    practice = page_text.get("practice.md", "")
    drills = [block for block in content.get("blocks") or [] if block.get("kind") == "drill"]
    if drills:
        rendered = len(re.findall(r"(?m)^### ", practice))
        if rendered < len(drills):
            errors.append(
                f"course {code}: practice.md 的 AI 练习小节数 {rendered} 少于 content.json 的 drill 块数 {len(drills)}"
                "（AI 块未渲染到页面）"
            )
        missing_ids = [b["point_id"] for b in drills if b.get("point_id") and b["point_id"] not in practice]
        if missing_ids:
            errors.append(
                f"course {code}: practice.md 缺少 {len(missing_ids)} 个 drill 的考核点锚点（首个 {missing_ids[0]}）"
            )
        if not re.search(r"(?m)^<details>|^<details ", practice):
            errors.append(f"course {code}: practice.md 的 AI 练习答案未折叠（缺 <details>）")

    plan = page_text.get("plan.md", "")
    stages = content.get("stage_plan") or []
    rendered_stages = re.findall(r"(?m)^### 阶段：(.+?)\s*$", plan)
    expected_names = [str(stage.get("stage")) for stage in stages if stage.get("stage")]
    if rendered_stages != expected_names:
        errors.append(
            f"course {code}: plan.md 的 `### 阶段：` 小节 {rendered_stages} 与 stage_plan 的五阶段 {expected_names} 不一致"
            "（stage_plan 未渲染到页面）"
        )
    for stage in stages:
        name = stage.get("stage")
        done_when = stage.get("done_when")
        if done_when and done_when not in plan:
            errors.append(f"course {code}: plan.md 缺少阶段「{name}」的完成标准（done_when 未渲染）")
        for key, label in (("goal", "目标"), ("inputs", "输入"), ("how", "做法"), ("outputs", "输出物")):
            values = [str(item) for item in stage.get(key) or []] if isinstance(stage.get(key), list) else [stage.get(key)]
            if any(value and value not in plan for value in values):
                errors.append(f"course {code}: plan.md 缺少阶段「{name}」的{label}（stage_plan 未完整渲染）")

    # 课程级 `exam_strategy`（W1）：必须落在 `plan.md` 的 `## 应试策略` 区块**之内**，
    # 而不是碰巧出现在页面别处（与 review 的命名缺口同一口径）。
    strategies = [block for block in content.get("blocks") or [] if block.get("kind") == "exam_strategy"]
    for block in strategies:
        block_id = block.get("block_id")
        section = re.search(r"(?ms)^## 应试策略\s*$(.*?)(?=^## |\Z)", plan)
        if section is None:
            errors.append(
                f"course {code}: plan.md 缺少 `## 应试策略` 区块（AI 课程级块 {block_id} 未渲染到页面）"
            )
            continue
        text = str(block.get("text_md") or "").strip()
        if text and text not in section.group(1):
            errors.append(
                f"course {code}: plan.md 的 `## 应试策略` 区块缺少 {block_id} 的 text_md（exam_strategy 未渲染）"
            )

    review = page_text.get("review.md", "")
    schedule = content.get("review_schedule") or {}
    if schedule.get("status") == "named_gap":
        # 缺口必须**在命名缺口区块内**呈现，而不是碰巧出现在页面别处
        block = re.search(r"(?ms)^## 命名缺口\s*$(.*?)(?=^## |\Z)", review)
        if block is None:
            errors.append(f"course {code}: review.md 缺少 `## 命名缺口` 区块（排程缺口未渲染）")
        else:
            for key, label in (("gap_impact", "缺口影响"), ("next_evidence", "下一份需要的证据")):
                value = schedule.get(key)
                if value and value not in block.group(1):
                    errors.append(
                        f"course {code}: review.md 的命名缺口区块缺少 {label}（{key} 未渲染）"
                    )
    else:
        for plan_entry in schedule.get("plans") or []:
            tier = plan_entry.get("tier")
            if tier and f"（{tier}）" not in review:
                errors.append(f"course {code}: review.md 缺少排程档位 {tier}（review_schedule 未渲染）")


def run_ai_content_gate(
    root: Path,
    *,
    rendered_course_dir: Path | None = None,
    course_code: str | None = None,
) -> list[str]:
    """校验 AI 备考层产物（默认校仓内页面；给定 `rendered_course_dir` 时校该目录，供暂存区复用）。"""
    errors: list[str] = []
    courses_dir = root / "sources" / "jiangsu" / "courses"
    if not courses_dir.is_dir():
        return errors

    markers = course_pages_contract.generated_page_markers(course_pages_contract.load_schema(root))

    for course_dir in sorted(courses_dir.iterdir()):
        if not course_dir.is_dir():
            continue
        content_path = course_dir / "content.json"
        if not content_path.is_file():
            continue

        code = course_dir.name
        if course_code is not None and code != course_code:
            continue
        rel_content = content_path.relative_to(root).as_posix()

        try:
            content = json.loads(content_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"{rel_content}: JSON decode error: {exc}")
            continue

        model_path = course_dir / "knowledge-model.json"
        if not model_path.is_file():
            errors.append(f"course {code}: content.json exists but knowledge-model.json missing")
            continue

        try:
            model = json.loads(model_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"course {code} knowledge-model.json: JSON decode error: {exc}")
            continue

        # 1. `stage_plan[]` 恰 5 条（错误文案需点名「5」）
        stage_plan = content.get("stage_plan")
        if not isinstance(stage_plan, list) or len(stage_plan) != 5:
            n_stages = len(stage_plan) if isinstance(stage_plan, list) else "non-list"
            errors.append(f"course {code} stage_plan: 必须恰为 5 个阶段 (found {n_stages})")

        # 2. 标注四件套 / 块归属 / drill 字段
        for p in validate_content_doc(content, model):
            errors.append(f"course {code}: {p}")

        # 3. 8-gram 与考纲语料重合率（语料 = evidence.json 指针 + sha256，缺失即失败关闭）
        syl_text = _syllabus_text(root, code, rel_content, errors)
        if syl_text:
            for p in plagiarism_violations(content, syl_text, threshold=0.20):
                errors.append(f"course {code} 8-gram overlap: {p}")

        # 4. 渲染页标记 + 文本边界 + AI 块是否真的落到页面
        rendered_dir = rendered_course_dir if rendered_course_dir is not None else (
            root / "content" / "jiangsu" / "courses" / code
        )
        if not rendered_dir.is_dir():
            # 有 `content.json` 却没有渲染页目录 = 「AI 块从未被渲染」的极端形态（B2a N-1）：
            # 旧实现在这里静默 `continue`，于是删掉整个课程页目录也全绿。
            errors.append(
                f"course {code}: 存在 {rel_content} 但渲染页目录不存在: {rendered_dir}"
                "（AI 备考层未渲染到页面）"
            )
            continue
        page_text: dict[str, str] = {}
        for md_file in sorted(rendered_dir.rglob("*.md")):
            rel_md = md_file.relative_to(rendered_dir).as_posix()
            text = md_file.read_text(encoding="utf-8")
            page_text[rel_md] = text
            # 页面分类按**相对路径**判定，报错文案才带课程前缀（前缀会破坏 glob 匹配）
            _page_problems(rel_md, text, markers, errors, label=f"course {code} {rel_md}")
        _page_reached_problems(code, content, page_text, errors)

    return errors
