"""AI Content Gate: validates AI prep layer contracts (Issue #55 / Task 6)."""
from __future__ import annotations

import json
from pathlib import Path

from lib.course_pipeline.generate_content import (
    plagiarism_violations,
    validate_content_doc,
)

OFFICIAL_PAGES = {"index.md", "syllabus.md", "sources.md"}
AI_PAGES = {"plan.md", "practice.md", "review.md"}
AI_BANNER_SUBSTR = "本页由 AI 辅助生成"
GENERATED_COMMENT_SUBSTR = "<!-- generated by scripts/build-course-content.py; do not edit -->"


def run_ai_content_gate(root: Path) -> list[str]:
    """Validate AI prep layer artifacts for courses that produce content.json."""
    errors: list[str] = []
    courses_dir = root / "sources" / "jiangsu" / "courses"
    if not courses_dir.is_dir():
        return errors

    syllabus_dir = root / "sources" / "jiangsu" / "processed" / "syllabus"

    for course_dir in sorted(courses_dir.iterdir()):
        if not course_dir.is_dir():
            continue
        content_path = course_dir / "content.json"
        if not content_path.is_file():
            continue

        code = course_dir.name
        rel_content = content_path.relative_to(root).as_posix()

        try:
            content = json.loads(content_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"{rel_content}: JSON decode error: {exc}")
            continue

        model_path = course_dir / "knowledge-model.json"
        if not model_path.is_file():
            errors.append(f"course {code}: content.json exists but knowledge-model.json missing")
            continue

        try:
            model = json.loads(model_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"course {code} knowledge-model.json: JSON decode error: {exc}")
            continue

        # 1. Run stage_plan check explicitly for error message mentioning "5"
        stage_plan = content.get("stage_plan")
        if not isinstance(stage_plan, list) or len(stage_plan) != 5:
            n_stages = len(stage_plan) if isinstance(stage_plan, list) else "non-list"
            errors.append(f"course {code} stage_plan: 必须恰为 5 个阶段 (found {n_stages})")

        # 2. Run validate_content_doc validations
        problems = validate_content_doc(content, model)
        for p in problems:
            errors.append(f"course {code}: {p}")

        # 3. Check 8-gram overlap with syllabus text
        syl_text = ""
        if syllabus_dir.is_dir():
            syl_matches = sorted(syllabus_dir.glob(f"{code}-*/document.extracted.md"))
            if syl_matches:
                syl_text = syl_matches[0].read_text(encoding="utf-8")
        if syl_text:
            plag = plagiarism_violations(content, syl_text, threshold=0.20)
            for p in plag:
                errors.append(f"course {code} 8-gram overlap: {p}")

        # 4. Check rendered markdown pages for banners and comments
        rendered_course_dir = root / "content" / "jiangsu" / "courses" / code
        if rendered_course_dir.is_dir():
            # Check root markdown files
            for md_file in sorted(rendered_course_dir.glob("*.md")):
                fname = md_file.name
                text = md_file.read_text(encoding="utf-8")
                rel_md = md_file.relative_to(root).as_posix()

                if GENERATED_COMMENT_SUBSTR not in text:
                    errors.append(f"course {code} {rel_md}: 缺少生成标识注释 <!-- generated by ... -->")

                if fname in OFFICIAL_PAGES:
                    if AI_BANNER_SUBSTR in text:
                        errors.append(f"course {code} {rel_md}: 官方页面意外包含 AI 横幅 banner（{AI_BANNER_SUBSTR}）")
                elif fname in AI_PAGES:
                    if AI_BANNER_SUBSTR not in text:
                        errors.append(f"course {code} {rel_md}: AI 页面缺少 AI 横幅 banner（{AI_BANNER_SUBSTR}）")

            # Check knowledge chapter markdown files
            rendered_km_dir = rendered_course_dir / "knowledge"
            if rendered_km_dir.is_dir():
                for md_file in sorted(rendered_km_dir.glob("*.md")):
                    text = md_file.read_text(encoding="utf-8")
                    rel_md = md_file.relative_to(root).as_posix()
                    if GENERATED_COMMENT_SUBSTR not in text:
                        errors.append(f"course {code} {rel_md}: 缺少生成标识注释 <!-- generated by ... -->")
                    if AI_BANNER_SUBSTR not in text:
                        errors.append(f"course {code} {rel_md}: AI 知识点页面缺少 AI 横幅 banner（{AI_BANNER_SUBSTR}）")

    return errors
