"""AI Content Gate: validates AI prep layer contracts (Issue #55 / Task 6).

覆盖对象 = **存在 `content.json` 的课程**（作用域规则：新层只对存在产物的课程生效，
其余 17 门课保持全绿）。四类校验：

1. **标注四件套**（`validate_content_doc`）：`blocks[]` / `stage_plan[]` / `review_schedule` 及其 `plans[]`；
2. **8-gram 抄袭守卫**：语料取自 `evidence.json` 的 `syllabus.path`，并**校验 `sha256`**（QC1 F-5：
   旧实现按目录 glob 找语料、空即**静默跳过**，等于把闸门交给文件命名）；
3. **页面标记**：页面分类与标记字符串一律取自 `course.schema.json` 的 `generated_page_markers`
   （QC1 F-4 / QC3-003：schema 是唯一真源，同一规则不写两遍）；
4. **AI 块必须真正落到页面**（QC3-001 / C2-004）：`practice.md` 的 drill 数、`plan.md` 的五阶段、
   `review.md` 的排程，逐项与 `content.json` 对账 —— 这一条缺失正是「AI 备考层从未被渲染」能过关的原因。

`rendered_course_dir` / `course_code` 让 `build` 的 `gate` 阶段校验**暂存区**页面而不是仓内既有页面。
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from lib import course_pages_contract
from lib.course_pipeline.generate_content import (
    plagiarism_violations,
    validate_content_doc,
)

# 8-gram 之外的文本边界（plan § Data contracts 5 / design-notes §2 invariant 5）：`>` 引用块 ≤ 80 字符。
MAX_BLOCKQUOTE_CHARS = 80
QUESTION_TEXT_RE = re.compile(r"(选择题|填空题|简答题|材料题|下列.*正确)")


def _syllabus_text(root: Path, code: str, rel_content: str, errors: list[str]) -> str:
    """考纲语料 = `evidence.json.syllabus.path` 的内容，且 `sha256` 必须与记录一致（缺失即失败关闭）。"""
    evidence_path = root / "sources" / "jiangsu" / "courses" / code / "evidence.json"
    if not evidence_path.is_file():
        errors.append(f"course {code}: content.json 存在但 evidence.json 缺失（无考纲语料可校验）")
        return ""
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    syllabus = evidence.get("syllabus") or {}
    rel_path = syllabus.get("path")
    if syllabus.get("status") != "extracted" or not rel_path:
        errors.append(f"course {code}: 考纲未 extracted（{rel_content} 的 8-gram 语料缺失，禁止静默跳过）")
        return ""
    document = root / rel_path
    if not document.is_file():
        errors.append(f"course {code}: evidence.json 指向的考纲抽取件不存在: {rel_path}")
        return ""
    recorded = syllabus.get("sha256")
    actual = hashlib.sha256(document.read_bytes()).hexdigest()
    if recorded != actual:
        errors.append(f"course {code}: 考纲抽取件 sha256 与 evidence.json 不一致（{rel_path}）")
        return ""
    return document.read_text(encoding="utf-8")


def _page_problems(rel_md: str, text: str, markers: dict, errors: list[str], *, label: str | None = None) -> None:
    """单页标记与文本边界（横幅双向断言 + generated 注释 + 生成页的引用块上限）。

    引用块上限只作用于**渲染器产出**的页面：`official_only` 页面（`index.md` / `syllabus.md` /
    `sources.md`）的正文是手写官方事实页，渲染器不得改写（QC3-002 / QC3-006 / C2-011）。
    对它们套用「≤ 80 字符」等于要求「删掉手写正文的引用块」，而那正是被判定的 Critical 缺陷本身。

    `rel_md` 是相对课程目录的路径（页面分类用），`label` 是报错前缀。
    """
    where = label or rel_md
    if markers["any"] not in text:
        errors.append(f"{where}: 缺少生成标识注释 <!-- generated by ... -->")

    is_official = course_pages_contract.matches_page(rel_md, markers["official_only"])
    is_ai = course_pages_contract.matches_page(rel_md, markers["ai_pages"])
    if is_official and markers["ai_banner"] in text:
        errors.append(f"{where}: 官方页面意外包含 AI 横幅 banner（{markers['ai_banner']}）")
    elif is_ai and markers["ai_banner"] not in text:
        errors.append(f"{where}: AI 页面缺少 AI 横幅 banner（{markers['ai_banner']}）")

    if is_official:
        return
    for line in text.splitlines():
        stripped = line.lstrip()
        if not stripped.startswith(">"):
            continue
        quote = stripped.lstrip(">").strip()
        if len(quote) > MAX_BLOCKQUOTE_CHARS:
            errors.append(f"{where}: 引用块超过 {MAX_BLOCKQUOTE_CHARS} 字符（{len(quote)}）: {quote[:40]}...")
        if QUESTION_TEXT_RE.search(quote):
            errors.append(f"{where}: 引用块出现题文特征: {quote[:40]}...")


def _page_reached_problems(code: str, content: dict, page_text: dict[str, str], errors: list[str]) -> None:
    """每个 AI 产物块都必须真的落到页面上（QC3-001 / C2-004：闸门只看页面装饰，看不出整层丢失）。

    对账口径按 kind：
    - `drill` → `practice.md` 的 `###` 小节数；
    - `stage_plan[]`（恰 5 条）→ `plan.md` 逐阶段名 + `done_when`；
    - `review_schedule` → `review.md` 的三档排程或命名缺口。
    """
    practice = page_text.get("practice.md", "")
    drills = [block for block in content.get("blocks") or [] if block.get("kind") == "drill"]
    if drills:
        rendered = len(re.findall(r"(?m)^### ", practice))
        if rendered < len(drills):
            errors.append(
                f"course {code}: practice.md 的 AI 练习小节数 {rendered} 少于 content.json 的 drill 块数 {len(drills)}"
                "（AI 块未渲染到页面）"
            )
        missing_ids = [b["point_id"] for b in drills if b.get("point_id") and b["point_id"] not in practice]
        if missing_ids:
            errors.append(
                f"course {code}: practice.md 缺少 {len(missing_ids)} 个 drill 的考核点锚点（首个 {missing_ids[0]}）"
            )
        if not re.search(r"(?m)^<details>|^<details ", practice):
            errors.append(f"course {code}: practice.md 的 AI 练习答案未折叠（缺 <details>）")

    plan = page_text.get("plan.md", "")
    stages = content.get("stage_plan") or []
    rendered_stages = re.findall(r"(?m)^### 阶段：(.+?)\s*$", plan)
    expected_names = [str(stage.get("stage")) for stage in stages if stage.get("stage")]
    if rendered_stages != expected_names:
        errors.append(
            f"course {code}: plan.md 的 `### 阶段：` 小节 {rendered_stages} 与 stage_plan 的五阶段 {expected_names} 不一致"
            "（stage_plan 未渲染到页面）"
        )
    for stage in stages:
        name = stage.get("stage")
        done_when = stage.get("done_when")
        if done_when and done_when not in plan:
            errors.append(f"course {code}: plan.md 缺少阶段「{name}」的完成标准（done_when 未渲染）")
        for key, label in (("goal", "目标"), ("inputs", "输入"), ("how", "做法"), ("outputs", "输出物")):
            values = [str(item) for item in stage.get(key) or []] if isinstance(stage.get(key), list) else [stage.get(key)]
            if any(value and value not in plan for value in values):
                errors.append(f"course {code}: plan.md 缺少阶段「{name}」的{label}（stage_plan 未完整渲染）")

    review = page_text.get("review.md", "")
    schedule = content.get("review_schedule") or {}
    if schedule.get("status") == "named_gap":
        # 缺口必须**在命名缺口区块内**呈现，而不是碰巧出现在页面别处
        block = re.search(r"(?ms)^## 命名缺口\s*$(.*?)(?=^## |\Z)", review)
        if block is None:
            errors.append(f"course {code}: review.md 缺少 `## 命名缺口` 区块（排程缺口未渲染）")
        else:
            for key, label in (("gap_impact", "缺口影响"), ("next_evidence", "下一份需要的证据")):
                value = schedule.get(key)
                if value and value not in block.group(1):
                    errors.append(
                        f"course {code}: review.md 的命名缺口区块缺少 {label}（{key} 未渲染）"
                    )
    else:
        for plan_entry in schedule.get("plans") or []:
            tier = plan_entry.get("tier")
            if tier and f"（{tier}）" not in review:
                errors.append(f"course {code}: review.md 缺少排程档位 {tier}（review_schedule 未渲染）")


def run_ai_content_gate(
    root: Path,
    *,
    rendered_course_dir: Path | None = None,
    course_code: str | None = None,
) -> list[str]:
    """校验 AI 备考层产物（默认校仓内页面；给定 `rendered_course_dir` 时校该目录，供暂存区复用）。"""
    errors: list[str] = []
    courses_dir = root / "sources" / "jiangsu" / "courses"
    if not courses_dir.is_dir():
        return errors

    markers = course_pages_contract.generated_page_markers(course_pages_contract.load_schema(root))

    for course_dir in sorted(courses_dir.iterdir()):
        if not course_dir.is_dir():
            continue
        content_path = course_dir / "content.json"
        if not content_path.is_file():
            continue

        code = course_dir.name
        if course_code is not None and code != course_code:
            continue
        rel_content = content_path.relative_to(root).as_posix()

        try:
            content = json.loads(content_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"{rel_content}: JSON decode error: {exc}")
            continue

        model_path = course_dir / "knowledge-model.json"
        if not model_path.is_file():
            errors.append(f"course {code}: content.json exists but knowledge-model.json missing")
            continue

        try:
            model = json.loads(model_path.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"course {code} knowledge-model.json: JSON decode error: {exc}")
            continue

        # 1. `stage_plan[]` 恰 5 条（错误文案需点名「5」）
        stage_plan = content.get("stage_plan")
        if not isinstance(stage_plan, list) or len(stage_plan) != 5:
            n_stages = len(stage_plan) if isinstance(stage_plan, list) else "non-list"
            errors.append(f"course {code} stage_plan: 必须恰为 5 个阶段 (found {n_stages})")

        # 2. 标注四件套 / 块归属 / drill 字段
        for p in validate_content_doc(content, model):
            errors.append(f"course {code}: {p}")

        # 3. 8-gram 与考纲语料重合率（语料 = evidence.json 指针 + sha256，缺失即失败关闭）
        syl_text = _syllabus_text(root, code, rel_content, errors)
        if syl_text:
            for p in plagiarism_violations(content, syl_text, threshold=0.20):
                errors.append(f"course {code} 8-gram overlap: {p}")

        # 4. 渲染页标记 + 文本边界 + AI 块是否真的落到页面
        rendered_dir = rendered_course_dir if rendered_course_dir is not None else (
            root / "content" / "jiangsu" / "courses" / code
        )
        if not rendered_dir.is_dir():
            continue
        page_text: dict[str, str] = {}
        for md_file in sorted(rendered_dir.rglob("*.md")):
            rel_md = md_file.relative_to(rendered_dir).as_posix()
            text = md_file.read_text(encoding="utf-8")
            page_text[rel_md] = text
            # 页面分类按**相对路径**判定，报错文案才带课程前缀（前缀会破坏 glob 匹配）
            _page_problems(rel_md, text, markers, errors, label=f"course {code} {rel_md}")
        _page_reached_problems(code, content, page_text, errors)

    return errors
