"""Course multipage structure + frontmatter schema contract."""
from __future__ import annotations

import fnmatch
import json
import re
from pathlib import Path

from lib.course_status import COMPLETENESS, LIFECYCLES
from lib.mdutil import split_frontmatter

DEFAULT_REQUIRED = {
    "index.md": ["页面导航", "sources.md", "practice.md", "plan.md"],
    "sources.md": ["来源", "核验"],
    "practice.md": ["真题"],
    "plan.md": ["阶段目标"],
}
CODE = re.compile(r"^[0-9]{5}$")

# `generated_page_markers`（Task 5 加进 `course.schema.json` 的键）是生成页标记的**唯一真源**：
# 暂存区检查与 `ai-content` 层都从这里取页面分类与标记字符串，避免同一规则写两遍而静默漂移。
DEFAULT_GENERATED_MARKERS = {
    "any": "<!-- generated by scripts/build-course-content.py; do not edit -->",
    "ai_banner": "本页由 AI 辅助生成",
    "ai_pages": ["plan.md", "practice.md", "review.md", "knowledge/*.md"],
    "official_only": ["index.md", "syllabus.md", "sources.md"],
}


def load_schema(root: Path) -> dict:
    path = root / "ops" / "jiangsu" / "schemas" / "course.schema.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _expand_page_patterns(patterns: list[str]) -> set[str]:
    return {str(pattern) for pattern in patterns}


def matches_page(rel: str, patterns: set[str]) -> bool:
    """页面相对路径是否命中 `generated_page_markers` 的页面模式（`plan.md` / `knowledge/*.md` / `knowledge/`）。"""
    return any(fnmatch.fnmatch(rel, pattern) or rel.startswith(pattern.rstrip("*")) for pattern in patterns)


def generated_page_markers(schema: dict) -> dict:
    """schema 的 `generated_page_markers`（缺键/缺项时回落默认值，保证新层不因 schema 缺失而静默跳过）。"""
    declared = schema.get("generated_page_markers") or {}
    markers = {
        key: declared.get(key, default)
        for key, default in DEFAULT_GENERATED_MARKERS.items()
    }
    return {
        "any": markers["any"],
        "ai_banner": markers["ai_banner"],
        "ai_pages": _expand_page_patterns(markers["ai_pages"]),
        "official_only": _expand_page_patterns(markers["official_only"]),
    }


def check_frontmatter(root: Path, index_path: Path, schema: dict) -> list[str]:
    errors: list[str] = []
    rel = index_path.relative_to(root).as_posix()
    text = index_path.read_text(encoding="utf-8", errors="replace")
    fm, _ = split_frontmatter(text)
    fm_spec = schema.get("frontmatter") or {}
    required = fm_spec.get("required") or ["lifecycle", "completeness"]
    life_vals = set(fm_spec.get("lifecycle_values") or LIFECYCLES)
    comp_vals = set(fm_spec.get("completeness_values") or COMPLETENESS)

    for key in required:
        if key not in fm or not str(fm.get(key, "")).strip():
            # allow status as legacy alias for lifecycle only during transition
            if key == "lifecycle" and fm.get("status") in life_vals:
                continue
            errors.append(f"{rel}: missing frontmatter `{key}`")

    life = (fm.get("lifecycle") or fm.get("status") or "").strip()
    if life and life not in life_vals:
        errors.append(f"{rel}: invalid lifecycle `{life}`")

    comp = (fm.get("completeness") or "").strip()
    if comp and comp not in comp_vals:
        errors.append(f"{rel}: invalid completeness `{comp}`")

    for key, reason in (fm_spec.get("disallowed") or {}).items():
        if key in fm:
            errors.append(f"{rel}: frontmatter `{key}` is disallowed ({reason})")
    return errors


def check_course_dir(root: Path, d: Path, schema: dict | None = None) -> list[str]:
    errors: list[str] = []
    if not CODE.fullmatch(d.name):
        return errors
    schema = schema or {}
    markers = schema.get("page_markers") or DEFAULT_REQUIRED
    required_files = schema.get("required_files") or list(DEFAULT_REQUIRED.keys())

    for filename in required_files:
        p = d / filename
        if not p.exists():
            errors.append(f"{d.relative_to(root).as_posix()}: missing {filename}")
            continue
        needles = markers.get(filename) or []
        text = p.read_text(encoding="utf-8", errors="replace")
        for needle in needles:
            if needle not in text:
                errors.append(f"{p.relative_to(root).as_posix()}: missing marker {needle}")

    index = d / "index.md"
    if index.exists():
        errors.extend(check_frontmatter(root, index, schema))
    return errors


def run_course_pages_contract(root: Path) -> list[str]:
    courses = root / "content" / "jiangsu" / "courses"
    errors: list[str] = []
    if not courses.is_dir():
        return [f"{courses.as_posix()}: courses dir missing"]
    schema = load_schema(root)
    for d in sorted(courses.iterdir()):
        if d.is_dir():
            errors.extend(check_course_dir(root, d, schema))
    return errors
